### ISSUE TITLE
Implement Travis

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#100]
It would be really handy if after ever push to the master branch and every PR, Travis CI were to run the tests and indicate whether the tests were passing.

This issue is a means of raising this as a feature request for discussion, with a view to it being implemented in a future release.

**Comment by glynnbird** [comment]
Note from @mikerhodes about how to get environment variable config into Travis http://docs.travis-ci.com/user/encryption-keys/. For when we get round to it.

**Comment by smithsz** [comment]
Done. Better late than never.
