### ISSUE TITLE
Geo support

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#101]
TBD, just capturing this for now

**Comment by komalda** [comment]
we also needed this feature.

**Comment by jhs** [comment]
Note, add some documentation about using it in the README

**Comment by rajrsingh** [comment]
Is this work complete @jhs? If not I can work on it. Do any of the Cloudant requests implement paging so that the user doesn't have to worry about getting back only the first 200 documents, or was that considered a bad idea?

**Comment by tomjessessky** [comment]
Hi @rajrsingh, I have a fork with an implementation, I will submit a PR later this week. Not sure about the 200 documents consideration...

**Comment by rajrsingh** [comment]
Great! Looking forward to it @tomjessessky

**Comment by jhs** [comment]
Done in 20df23c
