### ISSUE TITLE
mydb.find

### ISSUE THREAD

**Issue by arivatibm** [cloudant/nodejs-cloudant#104]
mydb.find does not seem to do anything when calling it 
is this a known issue?

**Comment by glynnbird** [comment]
the `find` function calls the /db/_find endpoint at Cloudant which is part of the Cloudant Query functionality.

Here's a working example:

```js
var Cloudant = require('cloudant');
var cloudant = Cloudant({ url: "https://reader.cloudant.com"});
var db = cloudant.db.use("guitars");
db.find({selector: { brand: "Fender"}}, function(err, data){
  console.log(err,data);
});
```

You will have had to create a working Cloudant Query index before querying.

See https://docs.cloudant.com/cloudant_query.html

**Comment by arivatibm** [comment]
mydb.list(...) works fine but mydb.index(...) and mydb.find(...) are not getting back from the callback
Can you see any issue with my code?

	var mydb = db.getDB("hazardevents");
	var startShift = getShiftBoundryTime(new Date(date),'start');
	var endShift = getShiftBoundryTime(new Date(date),'end');
	var query = {
			"selector": {
				"timestamp": {
					"$gte": startShift.toISOString(),
					"$lt": endShift.toISOString()
				}
			},
			"sort": [
			         {
			        	 "_id": "desc"
			         }
			         ]
	};
	
	mydb.index(function(er, result) {
		  if (er) {
		    throw er;
		  }
		  console.log('The database has %d indexes', result.indexes.length);
		  for (var i = 0; i < result.indexes.length; i++) {
		    console.log('  %s (%s): %j', result.indexes[i].name, result.indexes[i].type, result.indexes[i].def);
		  }
		  result.should.have.a.property('indexes').which.is.an.Array;
		  done();
		});
	
	var timestamp = {name:'timestamp', type:'json', index:{fields:['timestamp']}};
	mydb.index(timestamp, function(er, response) {		
	  if (er) {
	    throw er;
	  }
	 
	  console.log('Index creation result: %s', response.result);
	});
	
	mydb.find(query, function(err, doc) {
		if(err) {
			callback(err, null);		
		} else {
			callback(null, doc);
		}
	});

**Comment by glynnbird** [comment]
If I'm reading your code snippet correctly, you are

1) looking for a list of indexes (by calling `mydb.index()`)
2) creating a new index (`my.index(timestamp....`)
3) reading the result of a query (mydb.find)

It is best to wait for the index creation process to return before querying the index.

```
mydb.index(timestamp, function(er, response) {      
  if (er) {
    throw er;
  }

  console.log('Index creation result: %s', response.result);

  mydb.find(query, function(err, doc) {
    if(err) {
        callback(err, null);        
    } else {
        callback(null, doc);
    }
  });
});

**Comment by arivatibm** [comment]
still nothing is returning
even running the mydb.index() without any parameters is not returning

this is the version dependency on my package.json 
"cloudant": "^1.0.0"

**Comment by arivatibm** [comment]
fixed the index structure and now I get "undefined is not a function" on the mydb.find line

try {
		mydb.find(query, function(err, doc) {
			console.log(666);
			if(err) {
				console.log(777);
				callback(err, null);		
			} else {
				console.log(888);
				callback(null, doc);
			}
		});
	} catch (err)
	{
		console.log(JSON.stringify(err));
	}

**Comment by arivatibm** [comment]
apparently it was my bug - seems like the previous developer working on the code was using nano instead of cloudant package so the db.find function just doesn't exist in nano
the error message was a bit cryptic which took me some time to figure out
 
                                                                        Regards,
                         
                        Ari Volcoff                        Research Staff Member                        Smart Wearable and IoT Solutions - Smarter Business Solution Group                        IBM - Haifa Research Lab                                                                         
                                                                                                                                Mobile: +972-58-4168357 | Phone: +972-4-8281319                        E-mail: ARIV@il.ibm.com                        
 
 
----- Original message -----From: Glynn Bird <notifications@github.com>To: cloudant/nodejs-cloudant <nodejs-cloudant@noreply.github.com>Cc: Ari Volcoff/Haifa/IBM@IBMILSubject: Re: [nodejs-cloudant] mydb.find (#104)Date: Thu, Oct 22, 2015 5:54 PM 
If I'm reading your code snippet correctly, you are
1) looking for a list of indexes (by calling mydb.index())2) creating a new index (my.index(timestamp....)3) reading the result of a query (mydb.find)
It is best to wait for the index creation process to return before querying the index.
mydb.index(timestamp, function(er, response) {        if (er) {    throw er;  }  console.log('Index creation result: %s', response.result);  mydb.find(query, function(err, doc) {    if(err) {        callback(err, null);            } else {        callback(null, doc);    }  });});
—Reply to this email directly or view it on GitHub.
