### ISSUE TITLE
We should merge requestDefaults with ours, not replace ours

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#107]
See https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L38-L41

If the user provides `requestDefaults` then we use theirs. However, if they want to set a proxy or whatever, we will use the user-agent string. A better process would be to merge ours and theirs in some smart way.

**Comment by smithsz** [comment]
Fixed in https://github.com/cloudant/nodejs-cloudant/pull/243.
