### ISSUE TITLE
Cut out show, update, and list functions from the documentation

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#11]
In my opinion, _show, _list, and _update functions are not worth supporting officially. They are somewhere between confusing and useless, especially for a JavaScript client, where literally the exact same code can run client-side. Simplify, simplify. Remove them from the documentation (but leave them in the code) and just let it be a power user feature for those who want it.

**Comment by jhs** [comment]
Yes, for v1.1, I will remove this from the documentation. The API will still be there for people who know Nano, but I think #28 shows that this is a problem.

**Comment by jhs** [comment]
/cc @glynnbird @mikerhodes @xpqz 

If nobody objects, I will pull the trigger on this (i.e. do it) for the 1.1 release. By 2.0, with Nano as a dependency, people can use the Nano API as it will be available and documented in that project.

**Comment by jhs** [comment]
Another related paper cut is that `db.view_with_list()` could be confusing compared to the `db.list()` function. They do completely different things.

**Comment by glynnbird** [comment]
Fair enough. Not worth arguing about since v2 should be along in < 6 weeks. Go for it.
