### ISSUE TITLE
No compatible version found: nano@6.2.0

### ISSUE THREAD

**Issue by homerjam** [cloudant/nodejs-cloudant#116]
I'm getting this error when pushing to Heroku.

It looks like theres no such version of nano - weirdly I wasn't getting this problem an hour ago! Has something been rolled back/recently published that could cause this?

Thanks

**Comment by homerjam** [comment]
Also - what is the purpose of the `bundledDependencies` field in package.json?

**Comment by homerjam** [comment]
And why is there disparity in version numbers between this repo and npm?

**Comment by glynnbird** [comment]
Normally, nodejs-cloudant depends on a release of Nano. As Nano is now an Apache project, it's trickier to arrange releases of Nano which we can depend on. For version 1.4 of nodejs-cloudant, we decided to try a work-around: we would bundle the pre-release version of Nano in with our release of nodejs-cloudant (hence the bundleDependencies thing). 

This seems to work, but it is obviously causing you problems. We are working on a fix which should be released shortly. To avoid the problem, trying rolling back to nodejs-cloudant 1.3 which has a simpler dependency structure.

**Comment by homerjam** [comment]
Could you release a 1.3.2 version with all current fixes but using the old dependency structure?

I think in the long run maintaining a mirror of the apache version of nano (ie. as cloudant-nano) might be easier right? I actually use my own version of nano at the moment which includes some alterations to allow me to work locally with the couchdb-lucene plugin whilst using the same code to work with cloudant in production. The simple dependency stucture of 1.3.x allows this.

**Comment by jhs** [comment]
Hi! With v1.4.1, there are no more bundled dependencies, and if you want to use v1.4.0, you will see Nano v6.2.0 in the npm repository now.

I think that should solve your need for the old ways with 1.3.x; so I will close this ticket, but feel free to re-open if you still have a problem that I've overlooked. Thanks very much!
