### ISSUE TITLE
Cloudant packaged with dev dependencies

### ISSUE THREAD

**Issue by saxicek** [cloudant/nodejs-cloudant#118]
In version 1.4.0 development dependencies are bundled which makes the npm package quite big (28.8 MB vs. 6.7 MB). I am not experienced with `npm publish` but it seems that you should run `npm prune` before you publish.

The issue was also discussed in https://github.com/npm/npm/issues/11166 if you need more details how to reproduce.

**Comment by glynnbird** [comment]
The bundled dependency is a temporary fix while we try and get the Nano project published. When this happens, we can go back to the traditional "dependencies" method and the bundle size will drop back down again.

**Comment by saxicek** [comment]
Bundling is fine by me. But I guess there is no need to bundle Nano _development_  dependencies like istanbul which has ~5 MB.

**Comment by glynnbird** [comment]
ah. That is an oversight. Thank you for pointing this out. We'll attempt to fix that shortly cc @jhs

**Comment by jhs** [comment]
Hi! With v1.4.1, we are back to normal again: no bundled dependencies or anything like that. Please give it a try!

Thanks.
