### ISSUE TITLE
Nano repo is pointing to dscape/nano instead of apache/couchdb-nano

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#119]
Originally, Nano was 'npm publised' from the dscape/nano repository. Now it is published from the apache/couchdb-nano repo but the project's [package.json](https://github.com/apache/couchdb-nano/blob/master/package.json) still declares its home repo as the dscape/nano version.

This would be confusing to developers who want to browse the source code of the latest version of Nano.

**Comment by jhs** [comment]
Whoops, I "closed" it in the Nano project, not this one. Anyway, it's fixed in Git but I suppose it's not worth publishing a new version just for that. So it will be in the next npm release.
