### ISSUE TITLE
Switching to cookie authentication by default in this library

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#120]
There may come a day when passing the username and password using Basic Authentication with every request is penalised by the server. Best practice is to call `POST /_session` to exchange your credentials for a cookie. The cookie will expire eventually, so the library will have re-authenticate before the cookie expires.

This issue proposes that we:
- on instantiation of the Cloudant object issue a `POST /session` call to get a cookie
- subsequent library calls will not use the Cloudant object's username & password, but the cookie 
- the server may send us a new cookie when making a request. This must be user in place of the existing cookie from that point on

The above tasks need only be undertaken when a username & password are supplied i.e. not for local CouchDB requests in admin party mode.

In the case where a user has a long-running application which makes requests infrequently (less frequently than the cookie interval) then the user will need to do something like

```
  setInterval(function() {
    cloudant.ping(function(err, data) { } );
  }, 1000 * 60 * 60);
```

to ensure that the cookie stays fresh. 

---

The idea here is that by default, this library will always exchange authentication credentials for cookies and this will happen transparently for the user.

**Comment by jhs** [comment]
@glynnbird Do you know offhand, if the client is penalized for using basic auth, is that penalty implemented as a 429 code, or some other behavior? Do you know who might know?

**Comment by ricellis** [comment]
AFAIK there is no imposed penalty for using basic auth, only that it adds more overhead to each request than checking a cookie.

Most of the other Cloudant client libraries respond to `Set-Cookie` headers on all responses to refresh the cookie if the server has sent a replacement. They also attempt to renew the cookie when receiving the HTTP response codes:
* `401`
* `403` (when it has a reason of `credentials_expired`)

**Comment by glynnbird** [comment]
# Basic Auth vs Cookie Auth

Normally our library passes a user's credentials with every request:

```sh
curl https://uname:pwd@host.cloudant.com/db/_all_docs
```

This is fine but the preferred method is to get a session cookie by calling `POST /_session`

```sh
curl -v \
  -X POST \
  -d 'name=uname&password=pwd' \ 
  'https://host.cloudant.com/_session' 
```

Where Cloudant will reply with a cookie header:

```sh
Set-Cookie: AuthSession=xyz; Version=1; Path=/; HttpOnly; Secure
```

Future requests can work without passing the username and password, but passing in the cookie instead:

```sh
curl -v \ 
  --cookie 'AuthSession=xyz' \
  'https://host.cloudant.com/db/_all_docs'
```

This benefits us because our credentials are only occasionally sent over the wire, and Cloudant authenticates cookie-based requests faster than BasicAuth.

## In request land

We can achieve this using the `request` library like so:

```
var request = require('request');
var cloudanturl = 'https://host.cloudant.com';
var auth = {
  name: 'uname',
  password: 'password'
};

var r = {
  method: 'post',
  url: cloudanturl + '/_session',
  form: auth,
  jar: true
};
request(r, function(e, res, body) {
  console.log('auth', e, body);

  var r = {
    method: 'get',
    url: cloudanturl + '/a/_all_docs',
    jar: true
  };
  request(r, function(e, res, body) {
    console.log('fetch data', e, body);
  });
});
```

We are passing `jar: true` to *request* to instruct it to parse *Set-Cookie* headers and pass cookies back in future requests.

## In nodejs-cloudant

The least disruptive way of implementing cookie authentication into our library is to build a new plugin. As of v1.5 we have a means of defining plugins at runtime; a plugin being a request-compatible object. We have plugins to handle 429 replies (retry), Promises (promises) and simply use plain old *request* (default). I propose we create a new plugin (cookieauth) which handles this new behaviour. This will allow users to try out the feature without breaking default behaviour. In a future release then the 'cookieauth' plugin can become the 'default' behaviour, and we can look to unify all the plugins so we support cookies, 429s, Promises and streaming at the same time.

In broad brushstrokes, the aim is that when we start up the nodejs-cloudant library, we authenticate and get a session cookie. The user can then call library functions and we will make requests with the session cookie, replacing the cookie with a fresh one if Cloudant updates it.

```js
var url = process.env.CLOUDANT_URL;
var Cloudant = require('cloudant');
// at this point Cloudant will authenticate
Cloudant(url, function(err, cloudant) {
  var db = cloudant.db.use('mydb');
  
  // this will cause a cookie-based request
  db.get('zebra', function(err, data) {
  
  });
});
```

Let's look at this in more detail.

### Using with Apache CouchDB

If is possible to use *nodejs-cloudant* with a non-Cloudant service e.g. plain CouchDB. CouchDB 2.0 seems to have `GET /_session` and `POST /_session` but it's worth checking.

### Using without credentials

If no username/password is supplied to us at setup-time, then we must assume that the database is world readable/writable. We could call `GET /session` to see if we have *some* access rights, but needn't call the `POST /_session` endpoint because we have don't have a username or password to supply.

### Using with invalid credentials

If the wrong credentials are supplied, then Cloudant will

- return with HTTP 401 - Unauthorized
- clear out the AuthSession cookie

We can supply a suitable reply to a startup callback, but what do we do with future API calls?

### Using with the synchronous startup

You can also startup the Cloudant library synchronously:

```js
var url = process.env.CLOUDANT_URL;
var cloudant = require('cloudant')(url);
var db = cloudant.db.use('mydb');
  
// this will cause a cookie-based request
db.get('zebra', function(err, data) {
  
});
```

In our library's 'constructor' there's no harm in doing the first call to `POST /session` to get a cookie (despite the fact that we don't have a callback to return the data to the caller). But the call to `db.get` is certain to get called before we have a cookie.

Our code should detect that it has credentials but no cookie, so it needs to

- make a fresh `POST /session` request to exchange the credentials for a new cookie
- perform the required API call request sending the new cookie

### Handling updated cookies

Periodically Cloudant may choose to send our user-agent a fresh cookie. The `request` cookie jar should handle this but we need to test this use-case with careful mocked response. If the Cloudant library is used regularly, then the cookie should always be valid (see 'Handling expired cookies').

### Handling expired cookies.

If our library has a long time between requests, where the gap between requests exceeds the cookie lifetime, then it is possible for our cookie to be invalid when we come to use it.

We would not be able to detect that a cookie is invalid without actually making a request, in which case we'd get a `HTTP 401 Unauthorized` response.

Let's imagine a user was fetching a document - in this case we'd need to:

- make the GET /db/doc request and get a 401 request
- make a fresh `POST /session` request to exchange the credentials for a new cookie
- repeat the GET /db/doc request sending the new cookie

All of this would happen transparently for the user.

### Dealing with many concurrent requests

We should not try to optimise the use-case where lots of nodejs-cloudant library calls are being made 'in parallel', and potentially lots of different `POST /_session` requests are being fired off.

**Comment by rhyshort** [comment]
@glynnbird CouchDB does support the `_session` endpoint see http://couchdb.readthedocs.io/en/2.0.0/api/server/authn.html#cookie-authentication
