### ISSUE TITLE
text-like attachment has gzip problem when directly pipe into response

### ISSUE THREAD

**Issue by nosus** [cloudant/nodejs-cloudant#124]
My app is like this
web-client -> node.js(express) -> cloudant
On the node.js server, basically it wants allow user to post a file or get it later. 

The sample code for handling Get request of a file is below,  just directly pipe the attachment.get into the response. 

var attachment = db..attachment.get(resourceId, 'attachment', function (err) {
        if(!err) {
            console.log(res._headers);
            // at here, the http header does NOT have the Content-Encoding:gzip set, but the 
            // Content-Length is set to the 'gzipped' value
        } else {
             error(err, req, res, next);
        }
    });
});
console.log(res._headers);
//attachment.gzip = false;   <- If set the gzip to false, then in the above code, the response header has both Content-Encoding and Content-Length with correct value.  

var stream = attachment.pipe(response);

I find that for text-like resources, including content-type like:  text/plain, text/css, application/json,etc.  the return content for 'GET' is always less then the real content, it always miss some content at the end. 

After looking into the response header (nodejs->browser), I find the problem is:  the content-length is wrong. Basically the content-lengh has been set to the lengh of 'gzipped' content but the weird part is the 'content-encoding:gzip' is missing in the http header. So at client side, it get a much smaller content-length value which causes the problem above. 

Also, I find that if I turn off the 'gzip' in the Request object 
//attachment.gzip = false;
then everything is correct. 

It works fine for other binary data type like image because gzip doesn't happen.  

Not sure if it's related to the fix of https://github.com/cloudant/nodejs-cloudant/issues/72

**Comment by nosus** [comment]
I probably should mention the 'gzip' attribute on attachment is not a public variable. which means by default it's true.

**Comment by glynnbird** [comment]
The cloudant library's defaults are here:

https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L41

Our library indicates to the server that it is willing to accept gzip responses. Most Cloudant interactions are not gzip compressed (e.g. JSON document bodies, view results etc), but some attachments are - those whose mime-types match a list of  mime-types that Cloudant gzips.

Here's some sample code:

```js
var cloudant = require('cloudant');

var c = cloudant("https://reader.cloudant.com");
var db = c.db.use("attach");

var respond = function (err, data) {
  data = data.toString();
  console.log("err", err, "data", data);
}

db.attachment.get("bf5cd0234bff42c53c0bfc8cc3625f99", "guitars.txt", respond);
```

which fetches a `text/plain` attachment from Cloudant. This seams to work just fine. I put some debugging messages in and it does indeed get the compressed version of the text file but the library successfully unzips it before calling back with the data as a *buffer* (not a string).

If I change the code to pipe the output to `stdout` then it also works:

```js
var cloudant = require('cloudant');
var c = cloudant("https://reader.cloudant.com");
var db = c.db.use("attach");
db.attachment.get("bf5cd0234bff42c53c0bfc8cc3625f99", "guitars.txt").pipe(process.stdout)
```

I also note that if you want to override the gzip setting, you can do so by passing a "requestDefaults" object into the library when you fire it up

```js
  var cloudant = require('cloudant')( {url: "https://mydomain.cloudant.com", requestDefaults: { gzip: false} });
```

**Comment by nosus** [comment]
Hi glynnbird, thanks for the response. But the problem I met is not about getting the correct attachment content back, I think that part works if you just print it out or store it into file system using pipe. It's about the content-length and content-encoding header when using pipe. The the code in your comment

`db.attachment.get("bf5cd0234bff42c53c0bfc8cc3625f99", "guitars.txt").pipe(process.stdout)`

If you change the 'process.stdout' to an http response object, and log the http header of that reponse before and after the pipe, you will find there are several headers get set after the pipe, like 'content-length=**', but the problem is, this value is wrong because it's always the 'gzip' length, while there is no 'content-encoding=gzip' being set in the http header. So when you are using a web browser, you will find you can only get part of the content back, not all of them. 

Also, as I mentioned, even though I specified that I don't want the response get compressed, 'gzip=false', I still get the content back compressed and in the http header, both 'content-lenght=compressed-length' and 'content-encoding=gizp' are set.

**Comment by glynnbird** [comment]
So if I do:

```sh
curl -v 'https://reader.cloudant.com/attach/bf5cd0234bff42c53c0bfc8cc3625f99/guitars.txt' > /dev/null
```

I see a Content-Length of 17324, which happens to be the length of the text file.

If add `--compressed`:

```sh
curl -v --compressed  'https://reader.cloudant.com/attach/bf5cd0234bff42c53c0bfc8cc3625f99/guitars.txt' > /dev/null
```

then the Content-length becomes 6637, a reflection on the saving made due to compression. The uncompressed content is still 17324 bytes, but we only get to know that after decompressing the content. We know that the communication is gzipped because of the header `Content-Encoding: gzip`.

There is nothing in the headers that tells you the length of the content after compression. 

I suppose I'm saying that you can't use "Content-length" as an indicator of the size of the document you'll receive - it only indicates the quantity of data transferred between server and client.

As I said in my previous comment, if you want to switch off gzipping, you can do so:

```
var cloudant = require('cloudant')( {url: "https://mydomain.cloudant.com", requestDefaults: { gzip: false} });
```
