### ISSUE TITLE
Promise idea

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#128]
# Promises

Currently the nano/client expects a callback function to be provided that receives the data requested in a call to the library: 

```js
db.get('docid', function(err, data) {
  console.log(err, data);
}
```

It also returns the `request` object that represents the HTTP request that results from the call. This can be used to "pipe" data to other streams e.g.

```js
db.attachment.get('rabbit', 'rabbit.png').pipe(fs.createWriteStream('rabbit.png'));
```

If this library is to support Promises, then it needs to return something that can emit events so that the user can chain commands together. If we just returned a Promise, then users of the streaming functionality would fine that their code was broken.

At this point I found this library [https://www.npmjs.com/package/stream-to-promise](https://www.npmjs.com/package/stream-to-promise). It converts readable streams so that they are also promises.

Then we could change our code (the Nano 'relax' function actually) to convert the `request` object and emit events too, making it compatible with both streaming code and Promise users.

**Comment by jhs** [comment]
What about the PouchDB approach, where you run in callback mode if one is provided in the arguments, or you return a promise if a callback was not given?

Right now, I think nobody is using the Cloudant library and calling functions without providing any callbacks.

**Comment by glynnbird** [comment]
that's fine @jhs, but currently nano.relax returns the `request` object so that folks can use if for streaming the output. In order to maintain backward compatibility with this, we need to return something that is Promise compatible and also a stream thingy, hence https://www.npmjs.com/package/stream-to-promise.

**Comment by glynnbird** [comment]
If we swapped out 'request' in nano for https://www.npmjs.com/package/request-promise  then I think it would all just work because we always return the request object - the `request-promise` package just makes that promise friendly! What do you think @jhs?

**Comment by glynnbird** [comment]
But request-promise does warn "However, STREAMING THE RESPONSE (e.g. .pipe(...)) is DISCOURAGED because Request-Promise would grow the memory footprint for large requests unnecessarily high. Use the original Request library for that. You can use both libraries in the same project.".

**Comment by Thaina** [comment]
Support idea callback switch style

Should be easy to just wrap nano in promise and return if callback not exist
