### ISSUE TITLE
Mixing cfenv with cloudant causes misleading error

### ISSUE THREAD

**Issue by Nava2** [cloudant/nodejs-cloudant#129]
## Scenario

1. Using [`cfenv`](https://www.npmjs.com/package/cfenv) (e.g. running on Bluemix)
2. Using a hosted Cloudant instance
3. Get cloudant URL credentials from the cloud foundry environment through: `appEnv.getServiceURL()`
4. Initialize cloudant and run `db.index()`

## Not-working example

```js
// Init
const cfenv = require('cfenv');
const appEnv = cfenv.getAppEnv();

const Cloudant = require('cloudant');
const cloudant = Cloudant(appEnv.getServiceURL('Cloudant Storage'));

// Usage
const db = cloudant.db.use('my-db');
db.index((err, result) => {
  if (!!err) throw err; // THROWS
  console.log("Result: %o", result);
});
```

This throws an error with "Database does not exist." The reason is that `appEnv.getServiceURL()` returns a URL that ends with `/`, due to using the `url` library. 

## Proposed solution

In the `Cloudant` initialization, look for a trailing `/` and remove it. This error propagates into `nano` but it happens within a "typical" use case with Cloudant. 

Work-around is: 

```js
const cloudant = Cloudant(appEnv.getServiceURL('Cloudant Storage').slice(0, -1));
```

**Comment by glynnbird** [comment]
Good spot @Nava2. This is going on "the list" :)

**Comment by Nava2** [comment]
It's a pretty easy fix, I can do a PR if that's appropriate.

**Comment by glynnbird** [comment]
I like PRs even more than issues @Nava2 :)

**Comment by Nava2** [comment]
Great, I'll do it now. Just didn't want to step on anyone's toes!
