### ISSUE TITLE
Cannot parse \'/*%3A/*& error while calling search method

### ISSUE THREAD

**Issue by atulatgithub** [cloudant/nodejs-cloudant#132]
Hello,
I am making a search query on index from node.js
Code
db.search('all-states', 'allStates', {q:"*:*&counts=['State']&limit=0"}, function(er, result) {
  console.log("inside eeee");
  if (er) {
	//throw er;
  console.log(er);
}

Search is throwin below exception
===================================
{ [Error: Cannot parse '/*%3A/*&counts=[%22State%22]&limit=0': '*' or '?' not allowed as first character in WildcardQuery]
  name: 'Error',
  error: 'bad_request',
  reason: 'Cannot parse \'/*%3A/*&counts=[%22State%22]&limit=0\': \'*\' or \'?\' not allowed as first character in WildcardQuery',
  scope: 'couch',
  statusCode: 400,
  request: 
   { method: 'GET',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'https://XXXXXX:XXXXXX@b1611753-b3bf-47ce-95f7-0c67cc1a61a7-bluemix.cloudant.com/erpsalesdata/_design/all-states/_search/allStates',
     qs: { q: '/*%3A/*&counts=[%22State%22]&limit=0' } },
  headers: 
   { 'x-couch-request-id': 'dfc709bb29',
     date: 'Sat, 28 May 2016 09:59:33 GMT',
     'content-type': 'application/json',
     connection: 'close',
     'cache-control': 'must-revalidate',
     'strict-transport-security': 'max-age=31536000',
     'x-content-type-options': 'nosniff;',
     statusCode: 400,
     uri: 'https://XXXXXX:XXXXXX@b1611753-b3bf-47ce-95f7-0c67cc1a61a7-bluemix.cloudant.com/erpsalesdata/_design/all-states/_search/allStates' },
  errid: 'non_200',
  description: 'couch returned 400' }

I am able to run this query in browser without any issue.

@thiagoarrais 
@tarantoga

**Comment by atulatgithub** [comment]
Code is db.search('all-states', 'allStates', {q:"*:*&counts=['State']&limit=0"}, function(er, result)

**Comment by atulatgithub** [comment]
After q: code is star:star. Wildcard start.

**Comment by atulatgithub** [comment]
@jhs 
Hello Jason, I have raised this 2 days back. 
My work is blocked. If possible may i know who is right person who can comment/solve this?

Thanks in advance

**Comment by glynnbird** [comment]
You probably want something like this @atulatgithub :

```
var opts = {
  q: '*:*',
  counts: ['State'],
  limit:0
};
db.search('all-states','allStates',opts, callback);
```

**Comment by atulatgithub** [comment]
Hello Glynn.
Cool. Its working as per your suggestion.

Many many thanks.

**Comment by atulatgithub** [comment]
What is the syntax to include multiple colums in q:

ex : query is Makes:LG&Models:WD100CW&counts=["SKUs"]&limit=0
I want to include Make and Models in q:

I tried this var opts = { q: "Makes:" + make_name + "&" + "Models:" + model_name, counts: ["SKUs"], limit:0 };
But giving parsing error
@jhs

**Comment by glynnbird** [comment]
the query would be of the form:

`a:x AND b:y`

**Comment by atulatgithub** [comment]
Ok. Thanks Glynn
