### ISSUE TITLE
Getting 'error happened in your connection from' when behind proxy

### ISSUE THREAD

**Issue by atulatgithub** [cloudant/nodejs-cloudant#133]
Hello,
I was able to connect to using cloudant from my home.
However, from office network where my host is behind proxy, its failing

Getting 'error happened in your connection" error from connection.

@glynnbird

**Comment by glynnbird** [comment]
You can specify proxy server configurations when you initialises e.g.

```
  var opts =  {
    url: 'https://myusername:mypassword@myhost.cloudant.com',
    requestDefaults: {
      proxy : 'http://someproxy'
   }
  }
 var cloudant = require('cloudant')(opts);
```

see [Nano](https://github.com/apache/couchdb-nano) which this library is based on.
