### ISSUE TITLE
Bad request while running query

### ISSUE THREAD

**Issue by atulatgithub** [cloudant/nodejs-cloudant#134]
I have defined below inde
index("ZipCode", doc.Store.Zipcode, {"store": true, "facet": true});

And invoking below query
https://b1611753-b3bf-47ce-95f7-0c67cc1a61a7-bluemix.cloudant.com/erpsalesdata/_design/all-states/_search/allStates?q=*:*&counts=[“ZipCode”]&limit=0

However, getting below errot
{
•	error: "bad_request",
•	reason: "dim "ZipCode" does not exist"
}

@glynnbird

**Comment by glynnbird** [comment]
I see in the URL you have provided that "ZipCode" is surrounded by 'smart quotes'. e.g. “ instead ". Could that be the problem or is that just the way it is formatted in the ticket? I don't have read-access to the database so I can't see any further. Perhaps you could send an email to support@cloudant.com for this?

**Comment by jhs** [comment]
Hi, also, the `index()` function takes two arguments, but I think you are calling it with three. For example, here is the example of creating an index from the README:

``` js
var first_name = {name:'first-name', type:'json', index:{fields:['name']}}
db.index(first_name, function(er, response) {
  if (er) {
    throw er;
  }

  console.log('Index creation result: %s', response.result);
});
```
