### ISSUE TITLE
Grouping facets - counts

### ISSUE THREAD

**Issue by atulatgithub** [cloudant/nodejs-cloudant#136]
Hello,
I have states and cities.

Below is the index
function (doc) {
  index("State", doc.Store.State, {"store": true, "facet": true});
  index("City", doc.Store.City, {"store": true, "facet": true});
  if(doc.Zipcode) {
    index("Zipcode", parseInt(doc.Store.Zipcode,10), {"store": true, "facet": true});
  }
}

What I want is dinstinct cities in each state.
So gave below query.
https://<url>?q=State:Arizona,Washington&counts=["State"]&counts=["City"]&limit=0

Output
{
    total_rows: 13936,
    bookmark: "g2o",
   rows: [ ],
   counts: {
         City: {
                 Chandler: 3438,
                 Mesa: 3505,
                 Spokane: 3497,
                 Tucson: 3592,
                 Vancouver: 3420,
                Yuma: 3401
          }
}
}

The cities are mixing. I need the ouput per state.
What is the proper way to do this.

Thanks in advance.
@glynnbird

**Comment by glynnbird** [comment]
Two things to note here.

* facet *counts* only work on strings - as you are parsing your zipcode to an integer before indexing, it will be faceted but only for ranges - see https://docs.cloudant.com/search.html#faceting
* your query probably would be clearer if it was `q=State:Arizona OR State:Washington`

If you want unique counts for town/state pairs then that is the thing you should index e.g.

```js
function (doc) {
  index("State", doc.Store.State);
  index("CityState", doc.Store.City + "," + doc.Store.State, {facet: true}
}
```

Then when you query for `q=State:Arizona OR State:Washington` you should get counts for City/State pairs e.g. `"Seattle,Washington": 240`

**Comment by atulatgithub** [comment]
ok. Thanks. Let me try this.
