### ISSUE TITLE
get_security / set_security asymmetrical

### ISSUE THREAD

**Issue by srl295** [cloudant/nodejs-cloudant#139]
`db.get_security()` seems to return the entire `_security` record as per https://cloudant.com/for-developers/faq/auth/ 

``` js
{
  "_id": "security", 
  "cloudant": {
    "exampleuser1": [
      "_reader", 
      "_writer"
    ]
  }
}
```

however, `db.set_security(x)` does a `POST` to `_security`  with `{ cloudant: x }` 

so, if i'm trying to add user permissions for something, I can't do  `get_security()`, mutate the value with `x.user=['_reader']`, and just call `set_security(x)`. I end up with extra `cloudant: {}` objects in the security record that way.

**Comment by glynnbird** [comment]
Thanks. You're right we need to fix this. As it's a breaking change, we're putting this in for the 2.0 release.

**Comment by jhs** [comment]
Thanks! I think you make a good point. You've persuaded me that this is basically a bug.

Changing this will change the API, so this is in the 2.0 milestone. We plan to ship 2.0 after 1.7, which is just doing cookie authentication rather than basic auth. So we will work to ship this fix ASAP.

**Comment by toobstar** [comment]
Is there a stop gap solution to modifying an existing (or adding a new) permission with the current release API?

**Comment by smithsz** [comment]
Hey @toobstar, sorry for the delay. The `/_security` endpoint behaves a bit like the normal doc endpoint. So to avoid the `{ cloudant:` prefix thing you get with the `db.set_security` function, you could do something like this instead:
```js
> db.insert(securityObj, '_security', (err, body) => {
... console.log(err);
... console.log(body);
... });
```
Hope this helps.

**Comment by carloslfu** [comment]
Hi @smithsz I tried your solution but I have [this issue](https://github.com/cloudant/nodejs-cloudant/issues/84)
