### ISSUE TITLE
Not able to connect from other host

### ISSUE THREAD

**Issue by atulatgithub** [cloudant/nodejs-cloudant#142]
Hello,
I am able to connect to cloudant on my local host.
After copying the same code to other machine, cloudnat is giving below erroR

Failed to initilize cloudant. Error happened in your connection.

@glynnbird

**Comment by glynnbird** [comment]
Cloudant should be available from anywhere that has an internet connection. Try visiting your Cloudant URL in a web browser or by using `curl` on the command-line to verify your connection.

**Comment by atulatgithub** [comment]
ok. My host is behind corporate proxy. Mostly that may be the reason.
Thanks
