### ISSUE TITLE
connect to Cloudant local running on docker

### ISSUE THREAD

**Issue by clement360** [cloudant/nodejs-cloudant#143]
I'm trying to connect to a cloudant instance I have running in a docker container. 
I can connect via rest and throw the browser by hitting http://localhost:8080/

However using this package I'm getting auth errors. here is my connection:
var cloudant = Cloudant({hostname:"localhost:8080", username:"admin", password:"pass"});

![image](https://cloud.githubusercontent.com/assets/2770596/16927073/52cefc48-4cf1-11e6-8e03-4a64b51b5bcd.png)

**Comment by clement360** [comment]
Link to cloudant docker image: https://hub.docker.com/r/ibmcom/cloudant-developer/

**Comment by glynnbird** [comment]
Looks like you haven't specified the URL when you started up Cloudant. Try

```
   var cloudant = require('cloudant')('http://admin:pass@localhost:8080');
```

You can either supply a cloudant `account`, `username` and `password`, an object with a `url` in it or a string representing the url.
