### ISSUE TITLE
Keep-alive on by default

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#145]
When using nodejs-cloudant to communicate with a Cloudant cluster over HTTPS, it makes sense to keep a socket alive for because of the (performance) cost of setting up a TLS connection. This feature *can* be switched on in the library:

```js
// create custom HTTPS agent
var HttpsAgent = require('agentkeepalive').HttpsAgent;
var myagent = new HttpsAgent({
  maxSockets: 50, 
  maxKeepAliveRequests: 0,
  maxKeepAliveTime: 30000
});

// Setup Cloudant connection
var cloudant = require('cloudant')({ 
  url: 'https://myusername:mypassword@myaccount.cloudant.com', 
  "requestDefaults": { "agent" : myagent }
});
```

but by default, two requests separated by ten seconds would use two separate connections. 

This ticket is to remind us to align keep-alive, connection pooling and number of socket connection defaults with the other client libraries.

**Comment by kocolosk** [comment]
Any particular reason why you mentioned "ten seconds" there? What if it was just one second? 10ms?

A couple other questions:
- What does the `maxKeepAliveRequests` parameter do?
- What happens when a request all `maxSockets` have a request in flight? How does this behavior compare to the default node.js HTTP agent?

**Comment by glynnbird** [comment]
No real reason for 10 seconds, just that two operations that don't overlap would use separate connections, instead of sharing the first connection that was kept alive long enough to be reused.

- maxKeepAliveRequests but no longer features as a parameter in the [agentkeepalive](https://github.com/node-modules/agentkeepalive) project, so that needs removing
- not sure what happens when maxSockets is saturated - it appears to be set by "Infinity" by default

Here's the docs for the built-in HTTP agent: https://nodejs.org/dist/latest-v4.x/docs/api/http.html#http_class_http_agent, which offers the following options:

> - keepAlive <Boolean> Keep sockets around in a pool to be used by other requests in the future. Default = false
> - keepAliveMsecs <Integer> When using HTTP KeepAlive, how often to send TCP KeepAlive packets over sockets being kept alive. Default = 1000. Only relevant if keepAlive is set to true.
> - maxSockets <Number> Maximum number of sockets to allow per host. Default = Infinity.
> - maxFreeSockets <Number> Maximum number of sockets to leave open in a free state. Only relevant if keepAlive is set to true. Default = 256.

**Comment by kocolosk** [comment]
OK, so that sounds like the `keepAlive: true` behavior in the built-in agent is to reuse a free connection if possible; otherwise, spawn a new one. That seems like a smart default to me.

I'm guessing the built-in agent did not always support these options, hence the existence of `agentkeepalive`.

**Comment by glynnbird** [comment]
I agree. I think the outcome of this ticket would be to use Node.js's built-in agent with `keepAlive: true`, but also allow this to be overridden. I suspect there wasn't a built-in, keep-aliveable agent when this library was put together.

**Comment by jhs** [comment]
Ok, rolling this into v1.6, because I think this will interact with the Nano work we are doing, that gives us more control over the HTTP mechanism.

**Comment by jhs** [comment]
@glynnbird Don't we have `requestDefaults`? I am pretty sure we can supply an agent as a parameter to the request library.

**Comment by glynnbird** [comment]
@jhs that's what it says at the top of the ticket ;)
