### ISSUE TITLE
Can't use Node.js Cloudant to switch between CouchDB (locally) & Cloudant Remotely

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#15]
When developing an App, it may suit you to run against CouchDB on your own machine and against Cloudant in production.

The Cloudant Node.js library precludes this use-case as it insists on a *.cloudant.com domain name on connection.

Would it be possible to allow this library to be used against a local database as well as a hosted one, as Nano itself does?

**Comment by michaelbreslin** [comment]
Customers are now trying to use this library with Cloudant Local, so please update me when a version is ready that works with CouchDB/Cloudant Local and not just Cloudant DBaaS with the <account>.cloudant.com URI hard-coded.

**Comment by jhs** [comment]
However, to do this correctly will require comprehensive testing. Really, we would want a way to run the entire test suite against a Cloudant Local system. And in particular, we want to make sure the security and API key features work.

Those are all in scope for a 3.0 milestone, but for now I will check in a commit that closes this ticket the naïve way, by allowing an override of the hostname.

@michaelbreslin please let me know if customers have issues. And do you know how I can get access to a Cloudant Local system for testing? Thanks!

**Comment by michaelbreslin** [comment]
Jason,

Thanks for updating to allow for overriding the hostname so the library can
be used with both Cloudant Local and CouchDB.

I've cc: Mike Errington who can help you get access to a Cloudant Local
cluster to test things out.   Mike, Jason wrote the Node.js library...can
you help him out?

rgds,

Mike
