### ISSUE TITLE
plugins can't leverage requestDefaults

### ISSUE THREAD

**Issue by cjolif** [cloudant/nodejs-cloudant#151]
Plugins are supposed to be able to leverage requestDefaults. In particular in the promises plugin you can read:

https://github.com/cloudant/nodejs-cloudant/blob/master/plugins/promises.js#L23

However before the plugin is instantiated cloudant.js is removing requestDefaults from the options it is passing in the plugins:

https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L46:L66

One consequence is that I can't put request into "json" mode in the promises plugin which lead all cloudant APIs to return strings instead of JSON objects...

**Comment by glynnbird** [comment]
@cjolif Thanks for the heads up. Looking at this now.

**Comment by glynnbird** [comment]
Fixed in 1.5.1. Promises (resolve) now returns JSON where possible.
