### ISSUE TITLE
promises plugin does not expose error code

### ISSUE THREAD

**Issue by cjolif** [cloudant/nodejs-cloudant#152]
When an error occurs in querying Cloudant and you use the promises plugin the promise rejection error does not contain the statusCode which would be handy.

**Comment by glynnbird** [comment]
@cjolif This is an easy enough fix. Working on this now :)

**Comment by glynnbird** [comment]
Fixed in 1.5.1

**Comment by cjolif** [comment]
thanks for fixing #151 and this one, tested ok on my side.
