### ISSUE TITLE
'retry' plugin throw exception when no callback provided

### ISSUE THREAD

**Issue by thomas-mattsson** [cloudant/nodejs-cloudant#155]
If the 'retry' plugin is used, an exception is thrown if there is no callback provided with the cloudant call. For example: `cloudantDb.bulk({docs: myDocs});` and not `cloudantDb.bulk({docs: myDocs}, callback);`
Since that type of call is allowed with nano, a check if callback is defined should be done in the retry plugin before calling it.

**Comment by glynnbird** [comment]
Thanks for raising. This is fixed in 1.5.2.
