### ISSUE TITLE
What is the proper way to update a document?

### ISSUE THREAD

**Issue by ryanjbaxter** [cloudant/nodejs-cloudant#16]
What is the proper way to update a document using the node.js api?  I don't see an update function in the documentation, so are we supposed to use the insert function and supply the document id?  I would expect to also have to supply the revision as well.

**Comment by jhs** [comment]
Yes, to me it is mostly a documentation bug. It seems confusing that "insert" could either create or else update a document, depending on on field (_rev). For people who come from an SQL background, that is counter-intuitive.

Marking this for a fix in v1.1.

**Comment by glynnbird** [comment]
Improved the documentation.
