### ISSUE TITLE
Support new view parameters

### ISSUE THREAD

**Issue by rhyshort** [cloudant/nodejs-cloudant#169]
CouchDB 2.1.0 will include new view options to replace the existing `stale` parameter. These new parameters are shown in the table below with their mappings to the old API.

|# |	New API |      Old API   | Observed Behaviour (q=8,n=3)|
|--|----------|------------|--------------------------------|
|1|stable=true&update=true|Didn't exist|Blocks; Only 8 ushard indexers started|
|2|stable=true&update=false|stale=ok|Non-blocking; no indexers started; Matches previous API
|3|stable=true&update=lazy|stale=update_after|Non-blocking; 24 indexers started; Matches previous API|
|4|stable=false&update=true|stale not defined|Blocks; 24 indexers started; Matches previous API
|5|stable=false&update=false|Didn't exist|Non-blocking; no indexers started
|6|stable=false&update=lazy|Didn't exist|Non-blocking; 8 indexers started, all same node
------------

See [COUCHDB-3227](https://issues.apache.org/jira/browse/COUCHDB-3227)

**Comment by ricellis** [comment]
I don't think this is valid as Nano just accepts an object of query parameters so the new parameters should already be usable.
