### ISSUE TITLE
Add "sort" to the param keys that are encoded so that searches can be sorted

### ISSUE THREAD

**Issue by tsamsonWA** [cloudant/nodejs-cloudant#17]
I've updated my fork to add 'sort' to the list of possible params that are encoded in requests (nano.js, line 192).   Without it, attempting to do a sorted search returns an "invalid UTF-8 JSON" error.  I'm guessing others will want to use this feature.

I'm guessing this shouldn't be implemented by dropping it into Nano which is supposed to be just for CouchDB, and instead, it should go in the Cloudant wrapper since this is a Cloudant feature.  I've just put it there for now to unblock myself.

**Comment by jhs** [comment]
Fixed in d119334
