### ISSUE TITLE
How update a doc without overrid it?

### ISSUE THREAD

**Issue by david-araujo** [cloudant/nodejs-cloudant#170]
I have a doc:
{
   "_id" : "123abc",
    "_rev" : "1-abc56",
   "name" : "Jhon",
    "lastName" : "Doe"
}

Now I just want update the lastName, so I did the same example to update a doc (https://github.com/cloudant-labs/cloudant-nano#dbinsertdoc-params-callback):

db.insert( { _id:  "123abc", _rev: "1-abc56", lastName: "Something" }, function(err, data){
    console.log(data);
} );

The result was: 
{
   "_id" : "123abc",
    "_rev" : "2-abc56",
    "lastName" : "Something"
}

There is some other way to do this correctly, maybe using some set atribute?
And what about add a new field, I really have to rewrite all my document and add it?

**Comment by glynnbird** [comment]
When you update a document in Cloudant, you must supply the *whole* revised document. e.g.

db.insert( { _id: "123abc", _rev: "1-abc56", "name" : "Jhon", lastName: "Something" }, function(err, data){
console.log(data);
} );

**Comment by AftabFalak** [comment]
const newData={email:"aftabfalak956@gmail.com",name:"Aftab Falak"}
cloudant.use("user").find({selector:{_id:"user_id"}}, (err, documents) => `{`
    var revision = documents.docs[0]._rev;
    const data={...documents.docs[0],...newData};
    
    cloudant.use("user").insert(data,{_rev:revision},function(err){
        if (!err) {
            console.log('success', 'The record was updated successfully');
        }
        else {
            console.log('failure', err);
        }
    });
});
