### ISSUE TITLE
Error: error happened in your connection.

### ISSUE THREAD

**Issue by micophilip** [cloudant/nodejs-cloudant#172]
I started experiencing the following error when we’re trying to get a document from cloudant yesterday:
```
Error: error happened in your connection.
at Request._callback (/home/vcap/app/node_modules/cloudant/node_modules/nano/lib/nano.js:199:16)
```
We’re using the following settings for our cloudant connection pool (default from cloudant document using agentkeepalive package:
maxSockets: 50,
maxKeepAliveRequests: 0,
maxKeepAliveTime: 30000

Any idea what could possible be causing this error? it seems to happen after a while of extensive cloudant use (bulk inserts, multiple gets, ... etc)

**Comment by smithsz** [comment]
Apologies for the lack of communication. Please email support@cloudant.com if you are still experiencing service interruptions.
