### ISSUE TITLE
which cloudant-local is compatible with the different nodejs-cloudant version?

### ISSUE THREAD

**Issue by smartmouse** [cloudant/nodejs-cloudant#180]
we have cloudant-local version 1.1.0  and 1.0.0.4 , 1.0.0.5, how do we know which version of cloudant or cloudant-nano will be compatible to the cloudant local version?
Is there a table to map things like that?   If we can create a table , that will be good.

**Comment by ricellis** [comment]
I'm not aware of any compatibility issues and I would expect any version of nodejs-cloudant to work with any version of Cloudant Local Edition. I'm not aware of any relating specifically to nodejs-cloudant, but where compatibility issues have existed we fix them in the latest releases so I would always recommend using the latest versions.

Have you got a specific compatibility issue to report?
