### ISSUE TITLE
I'm facing a problem with limit of 5 requests

### ISSUE THREAD

**Issue by ricardocunha** [cloudant/nodejs-cloudant#184]
Hi,

I was using a free tier at bluemix, but after upgrade for the standard plan I'm getting the following error:

You've exceeded your current limit of 5 requests per second for query class. Please try later.

So, the standard plan has a limit up to 50, but do I need to change something?

**Comment by glynnbird** [comment]
Sounds like you are being rate limited. I would direct your request to support@cloudant.com, quoting the domain name of your Cloudant instance.
