### ISSUE TITLE
async await syntax

### ISSUE THREAD

**Issue by adamski** [cloudant/nodejs-cloudant#189]
Can anyone provide an example of using the library with the `async` and `await` keywords?

I'm trying for example

```js
const cloudant = Cloudant({account:key, password:password, plugin:'promises'});
//...
async function getData(mydb) {
  let res = await mydb.get(docId);
  console.log(res.body);
}
```
But `res.body` is `undefined`, and trawling through `res` I cannot see anything to do with the response, so I'm wondering if the response is even there yet? I realise this may be more of an issue with the `request` module but thought I'd post here first.

**Comment by glynnbird** [comment]
The `await` keyword only works in functions marked as `async` for things that return a Promise, so you should be able to do:

```
async function myfunc() { 
   let d = await mydb.get(docId);
   console.log(d);
}  
```

when using this library with the 'promises' plugin.

**Comment by adamski** [comment]
see my edit above

**Comment by adamski** [comment]
I am wondering whether the issue is that the promises plugin is not actually being used; if I switch to promise-style with `.then()` statements I get errors like
```
TypeError: sayit.attachment.insert(...).then is not a function
```

**Comment by adamski** [comment]
I just realised a very silly mistake, I was looking at an unused synchronous call to instantiate the module, which was where I put the plugin property, not the async call I'm actually using....

**Comment by glynnbird** [comment]
np glad you got sorted.

**Comment by adamski** [comment]
To answer my question above re: content of the response from `await`, it is the body itself so as per your example you would do e.g.

```
async function getData(mydb) {
  let res = await mydb.get(docId);
  console.log(res); // Print out the document, e..g. res._id, res._rev etc
}
```
