### ISSUE TITLE
Public cloudant docs, Question

### ISSUE THREAD

**Issue by carloslfu** [cloudant/nodejs-cloudant#199]
As Bluemix user and software developer I would like to contribute to the [Cloudant documentation](https://console.bluemix.net/docs/services/Cloudant/basics/index.html#cloudant-basics). So, is possible to open source Cloudant docs? is there a plan for it?. An example of successfully open source docs is Microsoft VSCode, her docs are more maintainable and are hosted in [Github](https://github.com/Microsoft/vscode-docs).

**Comment by ricellis** [comment]
I believe the docs are already in GitHub, just follow the link on any docs page to [Edit in GitHub](https://github.com/IBM-Bluemix-Docs/Cloudant/blob/master/basics/index.md) it will, I believe, take you to the relevant markdown page in the [docs repository](https://github.com/IBM-Bluemix-Docs/Cloudant).
![docs_in_github](https://user-images.githubusercontent.com/10698320/28107460-cb530be2-66df-11e7-9404-5f0af311b29b.png)

**Comment by warmanaIBM** [comment]
Hello @carloslfu ,

@ricellis is completely correct. A full copy of the main Cloudant documentation source is in the github.com/IBM-Bluemix-Docs/Cloudant repository. You are very welcome to offer suggestions, issues, or contributions through the normal GitHub processes, or you can use the direct 'edit on github' link that is visible on each page.

Many thanks for your interest.

**Comment by carloslfu** [comment]
Great!, thanks @ricellis and @warmanaIBM.
