### ISSUE TITLE
Synchronous initialisation documentation

### ISSUE THREAD

**Issue by MattCollins84** [cloudant/nodejs-cloudant#20]
After a little browse of the code we realised that it was possible to do:
```
var cloudant = require('cloudant')({account: username, password: password});
```

This returned a valid cloudant option, without having to do the async side of things (although that does verify that the supplied username/password is valid). This is much better for our workflow, and it would be nice to include it in the docs!

**Comment by jhs** [comment]
Fixed in your PR, ce5aa66. Thanks!
