### ISSUE TITLE
Current version of "request" dependency has a known vulnerability

### ISSUE THREAD

**Issue by kjdelisle** [cloudant/nodejs-cloudant#202]
The version of request currently being used in this library makes use of a vulnerable release of tunnel-agent, see **https://snyk.io/vuln/npm:tunnel-agent:20170305** for details.

```
├─┬ cloudant@1.8.0
│ └─┬ request@2.76.0
│   └── tunnel-agent@0.4.3
```

**Comment by tomblench** [comment]
Closing, fixed in #203
