### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by neekrish** [cloudant/nodejs-cloudant#204]
Once in a week we hit this error ... 

{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'ECONNRESET',
  description: 'socket hang up',
  stacktrace: 
   [ 'Error: socket hang up',
     '    at createHangUpError (_http_client.js:254:15)',
     '    at TLSSocket.socketOnEnd (_http_client.js:346:23)',
     '    at emitNone (events.js:91:20)',
     '    at TLSSocket.emit (events.js:185:7)',
     '    at endReadableNT (_stream_readable.js:974:12)',
     '    at _combinedTickCallback (internal/process/next_tick.js:74:11)',
     '    at process._tickCallback (internal/process/next_tick.js:98:9)' ] }
- Cloudant (nodejs-cloudant) version(s) that are affected by this issue.
1.8
- Node version
engines.node (package.json):  6.9.5
       engines.npm (package.json):   4.2.0
- A small code sample that demonstrates the issue.

1. What should we do when we hit this error?
2. What's the root cause?

**Comment by smithsz** [comment]
Hi @neekrish. Please can you direct your enquiry to support@cloudant.com. I'd like to examine our server logs before proceeding. In order to do this I'll need your Cloudant account name (which I don't want you to have to state here). Look forward to hearing from you. Thanks.

**Comment by neekrish** [comment]
@smithsz Got the response from the cloudant team:
I checked our log system about the account "XXXXXXXXXXXXXX" and timestamp you mentioned: from 8/17/17 9:40:00.000 AM to 8/17/17 9:50:00.000 AM UTC, I can not find any problematic request, all the requests with user_agent nodejs-cloudant/1.8.0 were returned quickly with http status code 200/201.

**Comment by smithsz** [comment]
Okay, thanks. Let me do some more digging and I'll get back to you via the support ticket.

**Comment by smithsz** [comment]
I'm going to close out this stale ticket.

If you are still experiencing problems then I'd advise you use the [retry plugin](https://github.com/cloudant/nodejs-cloudant#request-plugins). This will automatically retry requests on socket errors and bad HTTP status codes.
