### ISSUE TITLE
db.find() neither returned docs nor error

### ISSUE THREAD

**Issue by matuagarwal** [cloudant/nodejs-cloudant#207]
- Cloudant (nodejs-cloudant) version(s) that are affected by this issue.
`1.8.0`
- Node version
 `6.10.x`
- Env
`US-South (production)`
- Time of Issue
`2017-07-31T16:51:13.69+0100`
- Able to recreate
`No, it happened once at above mentioned time`

- Sample code
```
  db.find({selector: {clusterId: clusterID}}, function (apierr, apis) {
        if (apierr) {
            logger.error("Getting the api's information is failed with err : " + apierr.stack);
        } else {
            logger.debug('Found ' + apis.docs.length + ' documents for apis'); // line -5
            // further code
            }
     }
```

In line-5 `apis.docs` came as undefined.

As per expected behavior, either it should throw error or it should return apis.docs but apis.docs coming as undefined and no error was returned.

**Comment by emlaver** [comment]
Hi @matuagarwal, your example code does not include line 5 `api.docs`.  Could you please share the rest of the code?

**Comment by matuagarwal** [comment]
It was apis.doc ( I wrongly mentioned as api.docs)
Its present in the above code snipped logger statement
```
logger.debug('Found ' + apis.docs.length + ' documents for apis'); // line -5
```
apis.docs came as undefined.

**Comment by emlaver** [comment]
@matuagarwal We're unable to reproduce this.  Could you please contact our support team at support@cloudant.com? They will be able to examine the server logs using your Cloudant account name (which should only be shared through support). Thanks!
