### ISSUE TITLE
Suggest Usage of dotenv in README

### ISSUE THREAD

**Issue by bradley-holt** [cloudant/nodejs-cloudant#21]
The `README.md` file says:

> To use this code as-is, you must first type ` export cloudant_password="<whatever>"` in your shell. This is inconvenient, and you can invent your own alternative technique.

It might be helpful to suggest the usage of [dotenv](https://www.npmjs.org/package/dotenv) here.

**Comment by jhs** [comment]
Oh, wow! Dotenv, where have you been all my life?

@bradley-holt are you thinking that we just use dotenv in the project itself (i.e. we just tell people what `.env` file to create, and nodejs-cloudant will DTRT), or are you suggesting just a more specific example, walking people through using dotenv in our documentation?

Thanks! Marking for 1.1 milestone.

**Comment by bradley-holt** [comment]
I was thinking more the latter, simply suggesting that people use dotenv and provide an example of how to do this.
