### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by rafaelyates** [cloudant/nodejs-cloudant#220]
Hi everyone, it would be nice to have the typescript support in the library, currently there's no types/cloudant , thanks

**Comment by ericmillin** [comment]
I came here to post this very issue. There are already typings for `nano`, so should be fairly simple, though would need to add the Promises as return types, I guess: https://github.com/mateusnroll/typed-nano/blob/master/lib/nano.d.ts

**Comment by tomblench** [comment]
I'm afraid this isn't a priority for us at the moment.

We have some work in progress to enable promises on nodejs-cloudant which may make future typescript integration easier.

**Comment by garrensmith** [comment]
I've created a PR for the types https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23762

**Comment by smithsz** [comment]
Release 2.1.0 has basic TypeScript support.

I've created https://github.com/cloudant/nodejs-cloudant/issues/289 to support `Promise` return types in the declaration files.
