### ISSUE TITLE
When will `debug` dependencies update change be released

### ISSUE THREAD

**Issue by dhmlau** [cloudant/nodejs-cloudant#229]
There's currently a security vulnerability: https://nodesecurity.io/advisories/534 , and updating `debug` dependencies to 3.1.0 would help.  I saw that's already fixed but not released yet. Just wondering when it will be released to npmjs?  Thanks! 

https://github.com/cloudant/nodejs-cloudant/blob/master/CHANGES.md#unreleased

**Comment by smithsz** [comment]
Hi, I've cut a new release. Please use @cloudant/cloudant version 1.9.0. Thanks.
