### ISSUE TITLE
Allow cookie to be specified during client construction

### ISSUE THREAD

**Issue by smithsz** [cloudant/nodejs-cloudant#248]
Avoid the `/_session` cookie retrieval by passing in a valid cookie.
```js
var c = cloudant({ url: 'http://localhost:5984', cookie: 'xxxxxxxx' });
```
This would use `request.jar().setCookie` under the hood.

Note there is no easy method of retrieving a cookie from `tough.CookieJar`.  It may be easier to put a `getCookie` method on the `cloudantClient` class that intercepts a ping request and pulls the cookie from the headers.

**Comment by ricellis** [comment]
We're not doing new features here.

Our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta) [supports a `NOAUTH`](https://github.com/IBM/cloudant-node-sdk#authentication) authentication mode that disables all built-in authenticators. Futher [custom headers can be added to all requests](https://github.com/IBM/ibm-cloud-sdk-common/#sending-http-headers-with-all-requests) so it is possible to put a custom cookie on every request should that be desired.
