### ISSUE TITLE
Sample code in README has error

### ISSUE THREAD

**Issue by benrondeau** [cloudant/nodejs-cloudant#25]
In the [Getting Started](https://github.com/cloudant/nodejs-cloudant#security-note) section, there is a code sample that has a simple yet profound error that causes the 'use' method to fail, resulting in a failure to do anything with your database.

Wrong:
```javascript
var alice = Cloudant.use('alice')
```
Corrected:
```javascript
var alice = cloudant.use('alice')
```

The only different is a lowercase 'c' in ```cloudant```, which in the example provided is the difference between the ```Cloudant``` module and the ```cloudant``` object passed into the connection function that ["represents the DB connection to the server"](https://github.com/cloudant/nodejs-cloudant#database-functions).

Thanks

**Comment by raydaly** [comment]
Agreed. This fixed the error I was seeing.
