### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN when connecting to Cloudant

### ISSUE THREAD

**Issue by richardm** [cloudant/nodejs-cloudant#26]
I get this error when trying to connect from behind a proxy with a self-signed certificate. Same code just fine when connecting from a different network. Is there a workaround for this? Could not find anything related to this in the docs or SO.

{ [Error: error happened in your connection]
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  description: 'SELF_SIGNED_CERT_IN_CHAIN',
  stacktrace: 
   [ 'Error: SELF_SIGNED_CERT_IN_CHAIN',
     '    at SecurePair.<anonymous> (tls.js:1370:32)',
     '    at SecurePair.EventEmitter.emit (events.js:92:17)',
     '    at SecurePair.maybeInitFinished (tls.js:982:10)',
     '    at CleartextStream.read [as _read] (tls.js:469:13)',
     '    at CleartextStream.Readable.read (_stream_readable.js:320:10)',
     '    at EncryptedStream.write [as _write] (tls.js:366:25)',
     '    at doWrite (_stream_writable.js:226:10)',
     '    at writeOrBuffer (_stream_writable.js:216:5)',
     '    at EncryptedStream.Writable.write (_stream_writable.js:183:11)',
     '    at write (_stream_readable.js:582:24)' ] }

**Comment by jhs** [comment]
Thanks for the heads-up!

This is the second proxy issue I've seen. I believe this may be due to an old version of Nano and its dependency, Request. In v1.1 I will merge with the latest release of Nano so I will let you know and we can see if you still have the issue then.

**Comment by jhs** [comment]
Hi, @richardm! Please update to the latest Cloudant release, v1.0.0 in npm. We merged the latest Nano release, so the fix for this should be included in that merge.

Please let me know if you still have any issues! Thanks again for reporting this bug.
