### ISSUE TITLE
Throwing exception 'Referer header required' for  bulk_get Method

### ISSUE THREAD

**Issue by mansura-habiba** [cloudant/nodejs-cloudant#268]
Please include the following information in your ticket.

- Cloudant (nodejs-cloudant) version(s) : 1.10.0
- Node version: v8.1.3
- A small code sample that demonstrates the issue.

function getBulk(dbName, callback) {
   
    var db = cloudant.db.use(dbName);
      db.bulk_get({docs:[ {id:'doc1'}, {id:'doc2'}]}, function(err,response) {
          if (err) {
              throw err;
          }
          callback(err, response);
      });
}

Throwing the following Exception 

Error: Referer header required.
    at Request._callback (/..../node_modules/cloudant-nano/lib/nano.js:248:15)
    at Request.self.callback (/..../node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/..../node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/..../node_modules/request/request.js:1085:12)

{"message":"Referer header required.","stack":"Error: Referer header required.\n    at Request._callback (/..../node_modules/cloudant-nano/lib/nano.js:248:15)\n    at Request.self.callback (/..../node_modules/request/request.js:186:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (/..../node_modules/request/request.js:1163:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (/..../node_modules/request/request.js:1085:12)\n    at Object.onceWrapper (events.js:314:30)","name":"Error","error":"bad_request","reason":"Referer header required.","scope":"couch","statusCode":400,"request":{"method":"post","headers":{"content-type":"application/json","accept":"application/json"},"uri":"https://XXXXXX:XXXXXX@xxxx.cloudant.com/dbName/_bulk_get","body":"{\"docs\":[{\"id\":\"doc1\"},{\"id\":\"doc2\"}]}"},"headers":{"x-couch-request-id":"c00276eb6f","date":"Mon, 29 Jan 2018 11:39:09 GMT","content-type":"application/json","cache-control":"must-revalidate","strict-transport-security":"max-age=31536000","x-content-type-options":"nosniff","x-cloudant-request-class":"lookup","x-cloudant-backend":"yyyyy","via":"1.1 yyyyyy","statusCode":400,"uri":"https://XXXXXX:XXXXXX@xxxxx.cloudant.com/dbname/_bulk_get"},"errid":"non_200","description":"couch returned 400"}, stack=Error: Referer header required.
    at Request._callback (/..../node_modules/cloudant-nano/lib/nano.js:248:15)
    at Request.self.callback (/..../node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/..../node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/..../node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)

I have also tried setting cors
cloudant.set_cors({ enable_cors: true, allow_credentials: true, origins: ["*"]}, function(err, data) {
        console.log(err, data);
    });

However, the same exception as above mentioned is thrown.

**Comment by smithsz** [comment]
Hi,
Unfortunately I'm unable to reproduce this locally.

Could you please rerun your repro script with the DEBUG=* environment variable set and forward the output to us? _Be sure to redact usernames/passwords from any output._

If you're running against Cloudant then please send this information via a support ticket and we can pick it up from there.

Thanks,
Sam

**Comment by ricellis** [comment]
Closing as inactive, please re-open if you are still experiencing issues.
