### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by gusdaud** [cloudant/nodejs-cloudant#269]
Hey, it looks like that the version that has being published to NPM (1.10.0) doesn't support multiple plugins yet.

Is there an eta for the latest version to be published yet ?

**Comment by smithsz** [comment]
Hi,
The work to support multiple plugins required an extensive change to the codebase. We want to ensure all existing functionality is working correctly so will be carrying out further testing this week and next. Once we're satisfied with the results then we'll cut the 2.0 release.
Thanks.

**Comment by gusdaud** [comment]
Cool. Thanks!

**Comment by smithsz** [comment]
Thanks for your patience. We've now released `@cloudant/cloudant@2.0.2` to NPM.

**Comment by gusdaud** [comment]
Thats so great. Thank you so much.
Regards
