### ISSUE TITLE
Remove Extraneous HTTP Request

### ISSUE THREAD

**Issue by bradley-holt** [cloudant/nodejs-cloudant#27]
I should be able to instantiate a configured `cloudant` object without it first making a connection to test the authentication credentials. This causes an extra HTTP request that the user did not intend to make to Cloudant. We should do what we can to minimize extraneous database access (no matter how trivial), as this can make a difference in high-load environments.

If my credentials are bad, simply error when I make the first "real" database request (rather than when I first instantiate the object). This error condition needs to be handled anyways (credentials can change and HTTP is a stateless protocol).

**Comment by bradley-holt** [comment]
Actually, it looks like this is possible. It would be good to document this. These seems to be how to do it:

```javascript
var cloudant = require('cloudant');
var connection = cloudant({account:me, password:password});
```

**Comment by glynnbird** [comment]
This was raised in Issue #20 and there's even an unmerged pull-request to fix the documentation!

**Comment by bradley-holt** [comment]
Closing as duplicate of #20.

**Comment by jhs** [comment]
Just to chime in: I think there is value in both. I myself feel like, no, a configured database object is useless until the credentials are confirmed--whether high-load or no.

However, (1) @glynnbird persuasively argues the case where I create a cloudant object many times in the same application, that would be wasteful (in network traffic and programmer effort), and (2) @bradley-holt that is a very good point about credentials changing mid-execution. I made a new ticket #44 to track this.
