### ISSUE TITLE
Does nodejs-cloudant supports TLS 1.2?

### ISSUE THREAD

**Issue by jjayabal** [cloudant/nodejs-cloudant#271]
This blog (https://www.ibm.com/blogs/bluemix/2017/06/announcing-upcoming-changes-best-practices-ibm-cloudant-replication-security/) states Cloudant recommends TLS 1.2. So wanted to know if nodejs-cloudant supports TLS 1.2? If yes, does it supports by default or is there any explicit way of enabling it?

- Cloudant (nodejs-cloudant) version
     1.10.0
- Node version
     6.11.2

**Comment by tomblench** [comment]
See here [advanced configuration](https://github.com/cloudant/nodejs-cloudant#advanced-configuration) for an example of how to set `requestDefaults` which are passed into the underlying `request` library.

The `request` project have documented the use of the `secureProtocol` option [here](https://github.com/request/request#tlsssl-protocol). Further reference for `secureProtocol` is given [here](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) and [here](https://www.openssl.org/docs/man1.0.2/ssl/ssl.html#DEALING-WITH-PROTOCOL-METHODS). So you will probably want to set this to `"TLSv1_2_method"`.

Note that this may already be the default method and whether certain SSL/TLS protocols are available will depend on the version of Node and the SSL libraries you have installed.

**Comment by jjayabal** [comment]
@smithsz , regarding your PR, I see this 
-----------
If your server enforces the use of TLS 1.2 then the nodejs-cloudant client will continue to work as expected (assuming you're running a supported version of Node/OpenSSL).

You can pass `secureProtocol: "TLSv1_2_method"` in the request options to enforce TLS 1.2 on all outgoing requests, for example:
------------

So wanted to know if `secureProtocol: "TLSv1_2_method"` is optional? ie. even without that all my outgoing requests will be based on TLSv1.2?

**Comment by smithsz** [comment]
Using `secureProtocol: "TLSv1_2_method"` will _enforce_ TLS 1.2 and ensure you don't get downgraded to less secure cipher by the remote server. However, this is an optional step.

The client supports TLS 1.2 out of the box assuming your Node/OpenSSL version is current. As part of the TLS handshake the client specifies a list of preferred ciphers (likely [these](https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite) if you haven't replaced them) so you'll default to TLS 1.2 anyway.

Thanks for the question. I'll update the PR to clarify this.
