### ISSUE TITLE
list() not working with promises plugin, returns request object

### ISSUE THREAD

**Issue by homerjam** [cloudant/nodejs-cloudant#274]
Please include the following information in your ticket.

- Cloudant (nodejs-cloudant) version(s) that are affected by this issue.

master

- Node version

8.x

- A small code sample that demonstrates the issue.

```
async () => {
  const db = new Cloudant({
    url: dbUrl,
    plugins: ['retry', 'promises'],
  }).db.use(dbName);

  const docs = (await db.list({ include_docs: true }));

// docs is a `Request` object, expected the response body
}
```

```
  const db = new Cloudant({
    url: dbUrl,
    plugins: ['retry', 'promises'],
  }).db.use(dbName);

  const docs = db.list({ include_docs: true }).then(() => {
  // error: .then is not a function
  });

```

**Comment by ricellis** [comment]
The `await` keyword only works in `async` functions.

For example:
```js
async function printDocList() {
  const docs = await db.list({ include_docs: true });
  console.log(docs);
}

printDocList();
```

**Comment by homerjam** [comment]
@ricellis I'd cut that line from my example. Note that it doesn't work with `.then` either.

**Comment by ricellis** [comment]
Which commit are you using?
de8cc80b7a2fc375bf5f91cf1db87fc7714a518c works for me with the example above and with a `.then()` example.

**Comment by smithsz** [comment]
Please re-open this issue if further action is required. Thanks.

**Comment by homerjam** [comment]
I'm using the latest release `2.0.2`. @ricellis you're [example](https://github.com/cloudant/nodejs-cloudant/issues/274#issuecomment-365318453) prints the request object for me.

**Comment by homerjam** [comment]
Sorry - just realised I'd not updated my `require()` to `@cloudant/cloudant`. Problem solved!

😊
