### ISSUE TITLE
db.atomic documentation

### ISSUE THREAD

**Issue by prem911** [cloudant/nodejs-cloudant#28]
The example in the documentation for db.atomic looks to be incomplete.
If we follow it as is, it doesnot work.
		db.atomic("myDesignDoc", "inplace", myID, {field: "FFF", value: true}, function (error, response) {
 			console.log(error+""+response);
		});

The design doc has
"updates": {
    "inplace": "function(doc,req){var field = req.body.field;var value = req.body.value; var message = field + ':' + value; doc[field] = value;return [doc,''];}"
  }

On the atomic api call, we get error
"Invalid data from external server: {<<"info">>, {[{<<"update_seq">>, <<"35-g1AAAAG9eJzLYWBg4MhgTmGQS0lKzi9KdUhJstDLTMo1MLDUS87JL01JzCvRy0styQGqY0pkSJL___9_ViIXqg4znDqSFIBkkj1YkxCqJmPcmhxAmuLBmhhAmuThmgwNcetKAOmqB-tiJNZHeSxAkqEBSAH1zYdaR4zHIBoXQDTuz0pkItZzEI0HIBrvQzUS5UGIzgcQnUBPMmUBAK2EjkE">>}, {<<"db_name">>,<<"mqa_db">>}, {<<"sizes">>, {[{<<"file">>,751056}, {<<"external">>,2416}, {<<"active">>,19539}]}}, {<<"purge_seq">>,0}, {<<"other">>,{[{<<"data_size">>,2416}]}}, {<<"doc_del_count">>,1}, {<<"doc_count">>,5}, {<<"disk_size">>,751056}, {<<"disk_format_version">>,6}, {<<"compact_running">>,false}, {<<"instance_start_time">>,<<"0">>}]}}"
The uri shown is https://<cloudant-url>/<db>/_design/<design_doc>/_update/<function name>/<document_id>
This is a wrong uri, it should have "updates" and not "_update"

If I paste the modified uri in a rest client
https://<cloudant-url>/<db>/_design/<design_doc>/updates/<function name>/<document_id>
and pass body as
{field:"FFF", value:true}
I get {"error":"conflict","reason":"Document update conflict."}
Thus the update with handler needs a correct example.

**Comment by jhs** [comment]
Thanks for this! In your rest client example, the URL is not correct. Was that a formatting or copy-paste error?

**Comment by prem911** [comment]
This looks like a formatting issues in pasting doubles slashes in github. The intention of raising this defect is that the sample example is not working.

**Comment by jhs** [comment]
Hi, @prem911, thanks for the update.

Personally, I would like to remove `.atomic()` completely. I think it is problematic, largely because the update is not even atomic. It is still possible to produce conflicts with the `.atomic()` function, and secondly, it is very difficult to use.

My advice is to use Transaction, which will give you real transactional updates: https://github.com/jhs/txn
