### ISSUE TITLE
Deprecate virtual host helpers

### ISSUE THREAD

**Issue by smithsz** [cloudant/nodejs-cloudant#285]
> On March 1st, 2018 Cloudant will be removing connectivity via HTTP and requiring HTTPS, and removing support for the virtual hosts feature. Customers accessing Cloudant via HTTP or using vhosts should stop doing so immediately.

Deprecate following functions:
- `add_virtual_hosts`
- `get_virtual_hosts`

**Comment by ricellis** [comment]
Fixed by #345
