### ISSUE TITLE
TypeScript - Configuration typings do not include "maxAttempt" parameter

### ISSUE THREAD

**Issue by carlomorgenstern** [cloudant/nodejs-cloudant#290]
Cloudant version: 2.1.0
Node version: 9.8.0

Code Sample: 
```
import * as Cloudant from '@cloudant/cloudant';
const instance = Cloudant({
  url: cloudantConnectionUrl,
  maxAttempt: 5,
  plugins: [
    'cookieauth',
    'promises',
    'retry',
  ],
});
```
leads to TS compiler error:
Argument of type '{ url: string; maxAttempt: number; plugins: string[]; }' is not assignable to parameter of type 'string | Configuration'.
  Object literal may only specify known properties, and 'maxAttempt' does not exist in type 'string | Configuration'.

**Comment by smithsz** [comment]
Whoops! Thanks @carlomorgenstern, looks like we missed `maxAttempt` in the declaration file.

We'll get it sorted and make sure it's included in the next release.

**Comment by carlomorgenstern** [comment]
Thanks for the quick response!
