### ISSUE TITLE
TypeScript - Typings for initialization function does not include optional 'ping' callback

### ISSUE THREAD

**Issue by carlomorgenstern** [cloudant/nodejs-cloudant#291]
Cloudant version: 2.1.0
Node version: 9.8.0

Code Sample:
```
import * as Cloudant from '@cloudant/cloudant';
Cloudant({
  url: cloudantConnectionUrl,
  plugins: [
    'cookieauth',
    'retry',
  ], 
}, (error: Error, cloudantInstance: Cloudant.ServerScope) => {
    console.log('error', error);
    console.log('cloudant', cloudantInstance);
  }
});
```

leads to TS compiler error:
Expected 1 arguments, but got 2.

**Comment by smithsz** [comment]
Another one! Sorry, the TS stuff has only recently gone in. Clearly the coverage isn't 100%. I'll be sure to get this corrected for the next release.

**Comment by carlomorgenstern** [comment]
Thanks! You can still call `.ping` after creating the cloudant ServerScope for now, since the typings for the method already exist.
