### ISSUE TITLE
Getting indices with index() errors with 'promises' plugin enabled

### ISSUE THREAD

**Issue by carlomorgenstern** [cloudant/nodejs-cloudant#292]
Cloudant version: 2.1.0
Node version: 9.8.0

Code Sample:
```
import * as Cloudant from '@cloudant/cloudant';
const cloudantInstance = Cloudant({
  url: cloudantConnectionUrl,
  plugins: [
    'cookieauth',
    'promises',
  ],
});
const myDb = cloudantInstance.db.use('my-db');
const indizes = await myDb.index().catch(error => console.log(error));
```

The error logged in the last line results in a 400 'invalid UTF-8 JSON' from an otherwise perfectly operating Cloudant instance. Not using the 'promises' plugin with the same Cloudant instance also works fine.

The error message and a quick look into the code leads me to believe that this library incorrectly tries to create an index without an input object instead of getting the indices from the database, because the `index` function (file: cloudant.js, line: 114) checks for a callback function argument, which isn't and shouldn't be available in 'promises' mode.

**Comment by smithsz** [comment]
Good spot. This looks like a longstanding bug.

I guess you can pass a noop callback in the meantime. I'll get a fix out soon.

**Comment by carlomorgenstern** [comment]
A noop callback didn't work for me today. I think this specific line is also missing the `return` that every other `nano.request` has, but I didn't look into the code much, so that's only a guess.

I fixed the problem on my side by promisifying the callback myself.

**Comment by smithsz** [comment]
@carlomorgenstern If you have time, would you mind reviewing https://github.com/cloudant/nodejs-cloudant/pull/296? I've added the missing `return` and also included an additional 'undefined' check on the `definition` argument. Hopefully this solves the issue. Thanks.
