### ISSUE TITLE
'Promises' plugin - Support 'header' object of nano callbacks

### ISSUE THREAD

**Issue by carlomorgenstern** [cloudant/nodejs-cloudant#293]
Cloudant version: 2.1.0
Node version: 9.8.0

Per nano's documentation, a nano callback always recieves three arguments: error, body and header.
As of my tests now, when using the 'promises' plugin of Cloudant with the functions coming from nano, the information in the 'header' object always gets lost, because the promises only resolve with the 'body' object. 

Because of this, for example, you cannot get the most current document revision via `db.head(docId)` when you have the 'promises' plugin enabled.

Code Sample:
```
import * as Cloudant from '@cloudant/cloudant';
const callbackCloudant = Cloudant({
  url: cloudantConnectionUrl,
  plugins: [
    'cookieauth',
    'retry',
  ],
});

const promiseCloudant = Cloudant({
  url: cloudantConnectionUrl,
  plugins: [
    'cookieauth',
    'promises',
    'retry',
  ],
});

const callbackDb = callbackCloudant.db.use('my-db');
const promisesDb = promisesCloudant.db.use('my-db');

callbackDb.head(docId, (error, body, header) => {
  // header:
  // { 'x-frame-options': 'DENY',
  // 'x-couch-request-id': '...',
  // etag: '"..."',
  // date: 'Tue, 20 Mar 2018 13:12:11 GMT',
  // statusCode: 200,
  // uri: ''
  // ..... }
});

const header = await promisesDb.head(docId);
// header -> { statusCode: 200 }
```

An example solution could be to include a flag along the lines of `includeHeader: true` which makes the promise resolve with `[body, header]` instead of just `body`

**Comment by smithsz** [comment]
Yeah, I like the `includeHeader: true` idea. And it means we won't need to release a new major version.

**Comment by carlomorgenstern** [comment]
It would also be nice to be able to enable this on a per-method-basis.

For my use case, I really need the header info for `db.head()`, but I also don't want to use destructuring for every single other method just because of this one use.

Stuff like `db.get(docId).then([body] => {...})` can look to programmers not familiar with the code like someone has mistaken the array brackets for normal brackets.
And you don't need to destructure `[body, header]` if you don't want to use the header information.

I'm not sure though, what a good solution for this would look like.

**Comment by bgold0** [comment]
Yes would love this, I'm running into this issue now.

**Comment by ricellis** [comment]
Closing. The [promises plugin hasn't been necessary since 3.x](https://github.com/cloudant/nodejs-cloudant/blob/master/api-migration.md#2x--3x) - the Nano promise for [`headDoc` resolves with the headers](https://github.com/apache/couchdb-nano/blob/77224ebfbceaef40db297fc9916283705bd1f122/lib/nano.js#L584).

Also our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta) resolves promises with a `response` that includes `status` `headers` and `result`. An example retrieving headers for `HEAD /{db}/{docid}` is [here](https://cloud.ibm.com/apidocs/cloudant?code=node#headdocument).
