### ISSUE TITLE
Force update document or partial update document with out rev

### ISSUE THREAD

**Issue by chaitanya11** [cloudant/nodejs-cloudant#300]
Counch db supports partial update which don't require `rev` and also supports force update.
Is there a way to do the same in cloudant?

**Comment by smithsz** [comment]
I think you're referring to update handlers. Yes, Cloudant does support these features. Please see the [docs](https://console.bluemix.net/docs/services/Cloudant/api/design_documents.html#update-handlers).

**Comment by smithsz** [comment]
There isn't an update handler helper within this library yet. You can use `cloudant.request(opts, callback)` though to make a custom request to the sever.

Let me know if you have further questions.

**Comment by chaitanya11** [comment]
@smithsz do you have any example for updating document with out revision, or force update using update handlers.?

**Comment by smithsz** [comment]
You always need the latest revision number. Partial updates in CouchDB are just update handlers under the hood.

AFAIK it's not possible to force update a document without the latest revision number. Can you share the example you're using from CouchDB?
