### ISSUE TITLE
Get document return 500 Error: function_clause

### ISSUE THREAD

**Issue by wanginvc** [cloudant/nodejs-cloudant#302]
Get instance document return below error sometime. However, later get the document again can successfully return.

Cloudant error:  { Error: function_clause#012    at Request._callback (/opt/manager/node_modules/cloudant-nano/lib/nano.js:248:15)#012    at Request.self.callback (/opt/manager/node_modules/request/request.js:186:22)#012    at emitTwo (events.js:106:13)#012    at Request.emit (events.js:191:7)#012    at Request.<anonymous> (/opt/manager/node_modules/request/request.js:1163:10)#012    at emitOne (events.js:96:13)#012    at Request.emit (events.js:188:7)#012    at IncomingMessage.<anonymous> (/opt/manager/node_modules/request/request.js:1085:12)#012    at IncomingMessage.g (events.js:292:16)#012  name: 'Error',#012  error: 'unknown_error',#012  reason: 'function_clause',#012  ref: 756084992,#012  scope: 'couch',#012  statusCode: 500,#012  request: #012   { method: 'GET',#012     headers: #012      { 'content-type': 'application/json',#012        accept: 'application/json' },#012     uri: 'https://XXXXXX:XXXXXX@XXXXXXX-bluemix.cloudant.com/instance/fd52d072e392a0d51aacf1f6828213a7' },#012  headers: #012   { 'x-frame-options': 'DENY',#012     'x-couch-stack-hash': '756084992',#012     'x-couch-request-id': 'b92682f708',#012     date: 'Tue, 17 Apr 2018 14:13:51 GMT',#012     'content-type': 'application/json',#012     'cache-control': 'must-revalidate',#012     'strict-transport-security': 'max-age=31536000',#012     'x-content-type-options': 'nosniff',#012     'x-cloudant-request-class': 'lookup',#012     'x-cloudant-backend': 'bm-cc-uk-02',#012     via: '1.1 lb1.bm-cc-uk-02 (Glum/1.50.4)',#012     statusCode: 500,#012     uri: 'https://XXXXXX:XXXXXX@XXXXX.cloudant.com/instance/fd52d072e392a0d51aacf1f6828213a7' },#012  errid: 'non_200',#012  description: 'couch returned 500' }\n

- Cloudant (nodejs-cloudant) version(s): 1.10.0
- Node version: 6.11.0
- Call below getInstanceById function sometime return 500 Error.
function get(db, id, callback) {
        db.get(id, function(err, result) {
            if(err) {
                callback(cloudantError(err));
                return;
            }
            callback(null, result);
        });
    }

exports.getInstanceById = function(id, callback) {
        get(ev.dbInstance, id, callback);
};

**Comment by smithsz** [comment]
There was some instability on our bm-cc-uk-02 cluster during this period. It's possible this was during a maintenance window and as a result some users may have experienced HTTP 500 errors for a short time. We apologise for the inconvenience this has caused. Please contact support@cloudant.com if you'd like to know more.
