### ISSUE TITLE
Return values when using Promises plugin not correct

### ISSUE THREAD

**Issue by s-rogers** [cloudant/nodejs-cloudant#308]
Please include the following information in your ticket.

- Cloudant (nodejs-cloudant) version(s) that are affected by this issue: Tested on 2.1.0 and 2.2.0
- Node version : v6.11.0
- A small code sample that demonstrates the issue.

This may be user error, but I'm struggling with the promises plugin.  Return values from a simple get seem to include a statusCode field in the body:

~~~~
const Cloudant = require('@cloudant/cloudant');
const cloudant = new Cloudant({ url: CDB_URL, plugins: [ 'promises', { retry: { retryDelayMultiplier: 4 } } ] });
    let db = cloudant.use("someDb");
    db.get("someId")
        .then((res) => {
            console.log(res)
       });
~~~~

The output would be something like:

{ endpoints: [],
  agentc:
   { switch:
      { certs: [Object],
        url: 'blah' } },
  statusCode: 200 }

which includes a statusCode.

The effects are worse when using attachments as db.attachment.get does not return a Byte stream, but an Object which includes a statusCode.

If I use regular callbacks, all works as expected.  Hopefully this is simple error on my part, but if someone could help me out that would be great.

**Comment by ricellis** [comment]
Looks like a bug.

**Comment by smithsz** [comment]
The addition of `statusCode` is a bug on our side (see linked PR for fix).

Using promises to get attachments is broken due to a bug in nano. The request headers aren't getting set correctly. Please use the workaround below whilst we work on a proper fix.

```js
var db = cloudant.db.use('mydb');
db.attachment.get('doc1', 'attachment.png', () => {}).then(function(data) {  // note noop callback
  fs.writeFile('attachment.png', data);
});
```

Let me know if you have any questions.
Thanks.
