### ISSUE TITLE
[meta] Add beta3 tag to this repo

### ISSUE THREAD

**Issue by kevinSuttle** [cloudant/nodejs-cloudant#31]
Can't seem to find it here, but it shows up in npm.

**Comment by jhs** [comment]
Hi, @kevinSuttle! What exactly shows up in npm that you cannot find here? Do you mean the beta3 version of the release?

**Comment by kevinSuttle** [comment]
Referring to the actual tag in git.

**Comment by glynnbird** [comment]
You are quite right @kevinSuttle. The repository doesn't have tags that match the npm release numbers, at least not for the v1.0.0-beta3 release. See <https://github.com/cloudant/nodejs-cloudant/releases>

**Comment by kevinSuttle** [comment]
Yep, beta 1 and 2 are here, but not 3. 
![screen shot 2015-03-22 at 10 22 34 pm](https://cloud.githubusercontent.com/assets/95672/6773647/06f6fba4-d0e2-11e4-87ee-94b300293e14.png)

**Comment by jhs** [comment]
Whoops, fixed! v1.0.0-beta3 tag pushed from my laptop. Sorry!
