### ISSUE TITLE
Mocha test runner execution hangs.

### ISSUE THREAD

**Issue by smithsz** [cloudant/nodejs-cloudant#310]
The tests don't exit cleanly. There are still handlers waiting to be executed that hold the node process open.

Revert [hack] and implement a proper fix.

[hack]: https://github.com/cloudant/nodejs-cloudant/pull/309/commits/e82b9fdcaf62772c90e1d5319686f1b3790e43cb

**Comment by emlaver** [comment]
Looks like it could be an issue in mocha version >= 4: https://github.com/mochajs/mocha/issues/3044

**Comment by emlaver** [comment]
@smithsz I added `process.exit()` to test `captures pipe event` and the tests exit without the need of `-- exit`: https://github.com/cloudant/nodejs-cloudant/commit/388bca58eb55bf7a7361158ab2a560854c9b88a5
