### ISSUE TITLE
Stale _rev is returned after doing multiple gets

### ISSUE THREAD

**Issue by micophilip** [cloudant/nodejs-cloudant#314]
- Cloudant version: 1.8.0
- Node version: 6.14.1
```
var _rev;
var Cloudant = require('cloudant');
var cloudant = Cloudant({
  account: host,
  username: userName,
  password: password
});

var db = cloudant(url).db.use(dbName);

function getCloudantDoc() {

  function callback(err, doc) {
    if (!err) _rev = doc._rev;
  }

  db.get(_id, callback);
}

setTimeout(getCloudantDoc, 60000);
```

We have code that gets the cloudant document by doing a `db.get` every minute. We noticed that after multiple gets, the cloudant document returned becomes stale with an old `_rev` returned and the only we can get a fresh `_rev` is by restarting the node.js server. Any reason why the document returned becomes stale after a while and how we can avoid that?

Thanks

**Comment by emlaver** [comment]
Hi @micophilip, are you using nodejs to also update the document?  How frequent is the document(s) updating? 

Have you tried getting the document every minute using `curl` or another client?

**Comment by micophilip** [comment]
@emlaver yes we are using `nodejs-cloudant` to insert as well.

The document update frequency varies (ranges from every few seconds to every few minutes) but we have approximately a total of 120 updates, and the `get` becomes stale as early as after the 65th update

Making a direct call using `curl` always returns the fresh `_rev`, it's only reproducible with the `nodejs-cloudant` client

**Comment by emlaver** [comment]
@micophilip Can you please update `nodejs-cloudant` to our latest version 2.2.0 and run your code again?

**Comment by micophilip** [comment]
@emlaver still reproducible with v2.2.0

**Comment by ricellis** [comment]
Does your real code handle errors more completely than the sample above? Your `callback` above suppresses errors and only updates the `_rev` var in a success case. If you are exceeding your plan limits and getting a `429 Too Many Requests` response, for example, the code above would suppress that and the `_rev` var would not get updated. I think this could give the *appearance* of a successful request returning an older rev.

There is no caching in this library so if you are genuinely being returned a "stale rev" then it will be coming from the server. There are a number of possibilities for the server sending something older than you think is the latest:

1. an eventual consistency situation and the nodes being contacted by the client have not yet received the latest updates

    >the only we can get a fresh _rev is by restarting the node.js server

    How long have you left your code running to validate that later revisions are not returned *eventually*?

2. the document has become conflicted by the updates and the winning `_rev` is the stale rev you are seeing (this doesn't seem the likely culprit given that you report that `curl` is able to get the newer rev)

    Nonetheless, have you validated that the document is not conflicted?

3. your updates are not successful so the latest rev is not what you think it is (again given that you report seeing the latest rev with curl this seems less likely)

    Are you handling errors returned by your update code?

**Comment by micophilip** [comment]
@ricellis 
1. Initially I had only 5 retries, then I thought it would eventually get the new `_rev` so I increased to 200, and then eventually to unlimited retries on the `get` that was running for about 2 hours, and I still got that same stale `_rev`

2. That is correct - `curl` always returned the fresh `_rev`. 

3. Updates were always successful - it's only the get that returns a stale `_rev` - the update with the stale `_rev` obviously returned 409.

We are checking for errors properly and yes we are handling errors returned by the update code - that was just a snippet to help facilitate explaining the issue.

Another (maybe interesting) finding is that only the retries on that particular get request gets stale, but if a new request is issued (from other areas of the code for example) they would get the fresh `_rev` so I thought maybe the culprit is `agentkeepalive` so I removed it from the picture completely and I still was able to reproduce the issue.

**Comment by micophilip** [comment]
update:
The code was doing this:
```
var _ = require('underscore')._;
existingDoc = doc;
newDoc = _.extend(existingDoc, changes);
newDoc._rev = doc._rev;
```
After that, `doc._rev` became equals to `newDoc._rev` which was the old `_rev` that was passed in the `changes` object. We needed to change that to this:
```
_rev = doc._rev;  //keep track of new _rev before merging with existingDoc
existingDoc = doc;
newDoc = _.extend(existingDoc, changes);
newDoc._rev = _rev;
```
And that worked and the "stale" behaviour is no longer reproducible.

Thanks @ricellis and @emlaver for your help - closing the issue
