### ISSUE TITLE
No equivalent of Initialization callback when using promsies plugin  

### ISSUE THREAD

**Issue by alexwood** [cloudant/nodejs-cloudant#329]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Using `promises` plugin. No equivalent behviour to the initialization callback. 
Checking initialization is really useful to allow us to find issues early on initialization of our application. 

eg 

something like this would be what I expected

```
let cloudant = Cloudant({ url: CDB_URL, plugins: 'promises' })
  .then(()=>{
    console.log('initialisation done', err)
  })
  .catch((err)=>{
    console.log('initialisation failed', err)
  })
```

### 2. What you expected to happen

I expected using promsies plugin to get a promise from initialization.
Therefore equivalent function to the initialzation callback

### 3. What actually happened

Initialization did not return a promise at all

## Environment details

version 2.3.0
Node.js version v8.9.4

**Comment by smithsz** [comment]
Yep, nice idea. I'll add it to the backlog.

In the meantime you can call the `ping` function yourself following the client instantiation.

For example:
```js
let cloudant = Cloudant({ url: CDB_URL, plugins: 'promises' })

cloudant.ping()
  .then((b)=>{
    console.log('initialisation done', b)
  })
  .catch((err)=>{
    console.log('initialisation failed', err)
  })
```

**Comment by ricellis** [comment]
Closing; won't fix.
