### ISSUE TITLE
IBM Cloud - IAM authorization support

### ISSUE THREAD

**Issue by AlexShkunov** [cloudant/nodejs-cloudant#332]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

IBM Cloud documentation introduces new way for Applications to authorize towards Cloudant service.

https://console.bluemix.net/docs/services/Cloudant/guides/iam.html

### 2. What you expected to happen
NPM Cloudant library to support new authorization mechanism

### 3. What actually happened
NPM Documentation has no mention of the new authorization mechanism

**Comment by smithsz** [comment]
Hi @AlexShkunov,
You'll need to add the `iamauth` plugin to your Cloudant client configuration. Take a look at the [plugins section](https://www.npmjs.com/package/@cloudant/cloudant#the-plugins) of the readme for more details.
Let me know if you have any further questions.
