### ISSUE TITLE
BasePlugin not exported

### ISSUE THREAD

**Issue by rhyshort** [cloudant/nodejs-cloudant#337]
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

- Attempt to import BasePlugin to create a custom plugin
- TypeError at Runtime/ Compiler error for TypeScript

```ts
import { BasePlugin } from `@cloudant/cloudant`
```

### 2. What you expected to happen

To be able to import BasePlugin in order to create a custom plugin

### 3. What actually happened

Compile error.

## Environment details
- Version(s) that are affected by this issue.
    > 2.3.0 
- Node.js version
    > v8.11.3

**Comment by wrumsby** [comment]
@smithsz as far as I can tell this is _not_ fixed - I still have problems with this running the latest version of the package - i.e. 4.4.2.
