### ISSUE TITLE
Error in webpack compilation for types (request) latest release 3.0.0

### ISSUE THREAD

**Issue by huineng** [cloudant/nodejs-cloudant#350]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 2. What you expected to happen
webpack compilation always worked utill i installed a few hours ago the latest release 3.0.0

### 3. What actually happened

```
ERROR in [at-loader] ./node_modules/@cloudant/cloudant/types/index.d.ts:16:8
    TS1192: Module '"/Users/guyhuinen/Documents/workspace/leap/leap/root/node_modules/@types/request/index"'has no default export.
```

## Environment details
node 11.2.0 npm 6.1  
typescript 3.1.6

using "request": "^2.88.0",

**Comment by smithsz** [comment]
Thanks @huineng. We've fixed this in version `3.0.1`.
