### ISSUE TITLE
Error with vcapServiceName in TypeScript

### ISSUE THREAD

**Issue by Save92** [cloudant/nodejs-cloudant#365]
### 2. What you expected to happen
Create Cloudant service with the vcap_services

### 3. What actually happened

Argument of type '{ vcapServiceName: string; vcapServices: any; }' is not assignable to parameter of type 'string \| Configuration'.
--

I think the vcapServiceName is missing in the cloudant Configuration parameters, so in TypeScript it's crashing

**Comment by ricellis** [comment]
Agreed, only the `vcapInstanceName` and `vcapServices` are currently listed in the TypeScript defs. @smithsz can you roll this into #359 along with the other broken TS things.

**Comment by smithsz** [comment]
Fixed in #369.
