### ISSUE TITLE
The "transfer closed with outstanding read data remaining" error is not thrown when abort stream connection.

### ISSUE THREAD

**Issue by smithsz** [cloudant/nodejs-cloudant#367]
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Mock CouchDB instance using express:
```js
const express = require('express')
const app = express()
const port = 3000

app.all('/*', (req, res) => {
  res.writeHead(200);
  res.write(' ')
  throw 'Err!'
  res.end()
})
app.listen(port, () => console.log(`Listening on port ${port}!`))
```
Attempt to get all databases:
```js
var cloudant = new Cloudant({
  url: 'http://localhost:3000'
});
cloudant.db.list(function() {
  console.log(arguments)
});
```
### 2. What you expected to happen
Get a network error.
### 3. What actually happened
Received following:
```
[Arguments] {
  '0': null, // <-- no error here!
  '1': ' ',
  '2':
   { uri: 'http://localhost:3000/_all_dbs',
     statusCode: 200,
     'x-powered-by': 'Express',
     date: 'Tue, 05 Feb 2019 16:51:18 GMT',
     connection: 'keep-alive',
     'transfer-encoding': 'chunked' } }
```
## Environment details
- Version(s) that are affected by this issue.
    > 3.0.2
- Node.js version
    > v11.8.0

**Comment by smithsz** [comment]
See underlying request bug [here](https://github.com/request/request/issues/2671).

**Comment by ricellis** [comment]
With the deprecation of `request` we're not going to get an upstream bug fix for this problem so it isn't going to get fixed here.

FWIW we haven't observed an issue like this in our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta).
