### ISSUE TITLE
insert method does not have a rev parameters

### ISSUE THREAD

**Issue by Aerex** [cloudant/nodejs-cloudant#37]
I would like to be able to overwrite design documents using the insert method without having to provide the revision number. Cradle has this ability it would be nice to see it here.

**Comment by jhs** [comment]
Thanks for the feedback!

That is a useful feature; however, I think it is a bit too dangerous for this mainline, general-purpose, library. The reason for the revision number is, that is how you demonstrate to Cloudant or CouchDB that you are deliberately, explicitly making the changes you mean. In other words, you are saying "given revision X, I now want to change it this way and that" and then Cloudant says "Okay, your change is now revision Y." It is kind of similar to how Git works.

To me, your idea sounds like a perfect plugin. I made a new label, "plugin" for this issue.

In the meantime, I would suggest a few ideas:

* Use Cradle. It has lots of things going for it. If it suits your style, then go for it!
* Use Txn, which is a more "correct" way to edit a document without worrying about revisions: https://github.com/jhs/txn

**Comment by glynnbird** [comment]
If you are interested in Design Document management in general, then this blog post goes through some best practices and links to some tools you can use to manage design documents at a higher level:

https://docs.cloudant.com/design_document_management.html

**Comment by glynnbird** [comment]
The underlying lack of information about the 'insert' method is fixed upstream in the Nano project with this commit: https://github.com/dscape/nano/commit/9bcb1829270ad021f801dab62621094478159992
