### ISSUE TITLE
Ionic-Angular 

### ISSUE THREAD

**Issue by Armandavari** [cloudant/nodejs-cloudant#384]
Hello,
Im Starting To Use Ionic v4. The starter Templayte are compile without errors. but when i copy files from this demo source ( https://github.com/ionic-team/ionic-preview-app/tree/master/src/pages/alerts/basic ) it fails to compile. and give this error :

ERROR in ./src/app/tab3/tab3.module.ts 16:58-66
[ng] "export 'Tab3Page' was not found in './tab3.page'
[ng] ERROR in ./src/app/tab3/tab3.module.ts 18:23-31
[ng] "export 'Tab3Page' was not found in './tab3.page'
[ng] ERROR in ./src/app/tab3/tab3.page.ts
[ng] Module not found: Error: Can't resolve './template.html' in 'C:\Users\ASUS\Ionic\app\src\app\tab3'
[ng] ERROR in ./src/app/tab3/tab3.page.ts
[ng] Module not found: Error: Can't resolve 'ionic-angular' in 'C:\Users\ASUS\Ionic\app\src\app\tab3'
[ng] Time: 797ms
[ng] i ｢wdm｣: Failed to compile.
[ng]
[ng]     ERROR in src/app/tab3/tab3.module.ts(6,10): error TS2305: Module '"C:/Users/ASUS/Ionic/app/src/app/tab3/tab3.page"' has no exported member 'Tab3Page'.
[ng]     src/app/tab3/tab3.page.ts(3,33): error TS2307: Cannot find module 'ionic-angular'.

**Comment by ricellis** [comment]
I'm closing this ticket as the issue template has not been completed and there is no information here that is indicative of a specific problem with the `nodejs-cloudant` library. We are unable to support your use of the Ionic framework - if their preview app isn't working I suggest you raise an issue with Ionic.

We have had reports before of issues using nodejs-cloudant in Ionic; see https://github.com/cloudant/nodejs-cloudant/issues/368 - the outcome there was that including [third-party libraries with Typescript into Ionic](https://github.com/ionic-team/ionic/issues/4986) is fraught with difficulty and seems to only work for a select few widely used libraries.

If you manage to isolate a problem to something specific with nodejs-cloudant please complete the template when opening a new issue to ensure we have the correct information to investigate the problem.

**Comment by Armandavari** [comment]
The preview template is working. I did mention this earlier. When I change the template code with this for example :

 import { Component } from '@angular/core';

import { AlertController } from 'ionic-angular';


@Component({
  templateUrl: 'template.html'
})
export class BasicPage {

  constructor(public alerCtrl: AlertController) { }

  doAlert() {
    let alert = this.alerCtrl.create({
      title: 'New Friend!',
      message: 'Your friend, Obi wan Kenobi, just approved your friend request!',
      buttons: ['Ok']
    });
    alert.present()
  }

}

It gaves that ionic-angular error

**Comment by ricellis** [comment]
So you are saying you can reproduce an ionic-angular error with that code sample that includes **no `nodejs-cloudant` code or imports**? This is why I'm telling you need support with Ionic/Angular - this repository is for the nodejs-cloudant library and you are reporting a problem that apparently has no nodejs-cloudant code involved.
