### ISSUE TITLE
CloudantDB permissions with Bluemix App

### ISSUE THREAD

**Issue by benrondeau** [cloudant/nodejs-cloudant#41]
Please see post [here](http://stackoverflow.com/questions/30145306/using-cloudantdb-as-a-service-for-a-bluemix-nodejs-app) and help me out! 

Thanks

**Comment by benrondeau** [comment]
Answer noted [here](http://stackoverflow.com/questions/30145306/using-cloudantdb-as-a-service-for-a-bluemix-nodejs-app/30145451#30145451)

**Comment by jhs** [comment]
Thanks for the follow-up!
