### ISSUE TITLE
deprecated dependent request lib

### ISSUE THREAD

**Issue by profhun** [cloudant/nodejs-cloudant#415]
Hi Team!

Please update the request package, because my yarn write this for me when i install:
```
[Balazs@localhost]$ yarn add @cloudant/cloudant
yarn add v1.22.0
[1/4] Resolving packages...
warning @cloudant/cloudant > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by ricellis** [comment]
We're working on a new Node library for Cloudant that won't have a dependency on `request`. We'll update this repo in due course.

**Comment by mumeshr** [comment]
@ricellis do you have ETA for this issue? We need an alternative very soon. So asking for it.

**Comment by ricellis** [comment]
You can get updates on our new library here: https://github.com/IBM/cloudant-node-sdk

Alternatively, if you prefer to stay with the Nano style you can follow work in Apache CouchDB Nano to replace `request` with `axios` here: https://github.com/apache/couchdb-nano/pull/208

>We need an alternative very soon

Although it is deprecated the [`request` package](https://www.npmjs.com/package/request) is not going away (you can see it is still downloaded over 16M times a week).

**Comment by mumeshr** [comment]
Thanks @ricellis, the request API is deprecated and cannot run Contrast to clear vulnerability test. So have to move to alternate solution sooner. 
I tried https://github.com/IBM/cloudant-node-sdk, but there is no status or ETA on solution. 
I will see if we can move to couchdb-nano. I do use one nano api in our application for attachments. Will see if that works on not.

**Comment by ricellis** [comment]
Our new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta) is available and does not have a dependency on `request`.

Nano 9.x is also recently released and replaces `request` with `axios` - we won't be getting that new Nano version as a dependency for nodejs-cloudant because of incompatibilities with our existing plugin structures.
