### ISSUE TITLE
This package is using deprecated request package as dependency

### ISSUE THREAD

**Issue by mumeshr** [cloudant/nodejs-cloudant#441]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
This package is using deprecated request package as dependency 
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

This package is using deprecated request package as dependency, no code issue, but vulnerabilities are showing in audit.
### 2. What you expected to happen
Update the package to use alternatives of request package that will fix the issue.
### 3. What actually happened
Deprecation of request package.
## Environment details

10.24.0.

**Comment by emlaver** [comment]
Hello @mumeshr, a similar issue was already opened with this request.  See #415 for more details.

We have a new [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/)(beta) library available and it does not have a dependency on `request`.

From the #415 ticket: Nano 9.x is also recently released and replaces `request` with `axios` - we won't be getting that new Nano version as a dependency for nodejs-cloudant because of incompatibilities with our existing plugin structures.

**Comment by mumeshr** [comment]
Thanks for the update Esteban.
I'm using nano also for handling attachments from cloudant DB. Do you have any solution for that without request package dependency.
Thanks,Umesh

    On Friday, April 9, 2021, 3:01:58 PM EDT, Esteban Laver ***@***.***> wrote:  
 
 


Closed #441.

**Comment by emlaver** [comment]
@mumeshr I would suggest using the latest [couchdb-nano](https://github.com/apache/couchdb-nano) 9.x version which replaces `request` with `axios`.

**Comment by mumeshr** [comment]
Thanks @emlaver I tried above option, when I moved my API from .insert to .post (As I need insert + Update). Sometime for same level of transactions DB is returning conflict error, because of first update was in process and second update tries it again. So updating documenting using new API suggested @ibm-cloud/cloudant postDocument is slower than insert. While using insert I used basic-auth to authenticate but now I'm using IAMAuthenticator. Please suggest some solution.

**Comment by mumeshr** [comment]
@emlaver I found that IamTokenAuth is not supporting caching token and it is slow. I implemented using our own token manager and sending BearerToken to DB. This request matches the speed of basic auth. So we are good now.
