### ISSUE TITLE
how to check if cloudant is up and ready something similar to /_up

### ISSUE THREAD

**Issue by hamedminaee** [cloudant/nodejs-cloudant#446]
is there any way I can check if cloudant is up and running using this cloudant module 
something similar to

`await axios.get(`https://username:password@mycouchdomainurl/_up`);`
?

**Comment by bessbd** [comment]
Hi @hamedminaee ,

What do you think about the [`ping()`](https://github.com/cloudant/nodejs-cloudant#initialization-callback) function?

**Comment by hamedminaee** [comment]
@bessbd  Nice I assume it is the same as _up? and it is not an expensive call?

**Comment by hamedminaee** [comment]
I confirm it is working thanks
