### ISSUE TITLE
Retry functionality

### ISSUE THREAD

**Issue by pheuberger** [cloudant/nodejs-cloudant#450]
Hey there, 

I saw you're not supporting the previous host of plugins, but will you natively support retrying failed requests in the future?

Cheers,
Philipp

**Comment by ricellis** [comment]
The available plugins in nodejs-cloudant are listed here: https://github.com/cloudant/nodejs-cloudant#the-plugins including the `retry` plugin.
If you are referring to the migration guide and https://github.com/IBM/cloudant-node-sdk/ - then my expectation is that retry functionality will be added there via the https://github.com/IBM/node-sdk-core.
