### ISSUE TITLE
Replicating databases using IAM Authentication

### ISSUE THREAD

**Issue by hedphuqz** [cloudant/nodejs-cloudant#451]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
If i try to run a replication between one DB to another, the replication will fail by default if i am using the IAM plugin, saying that `Error: unauthorized to access or create database <SOURCE_DB>`

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Load cloudant and use the IAM plugin for authentication with IBM Cloud.
Run `.replicate()` on any DB

```javascript
import * as Cloudant from '@cloudant/cloudant'
const cloudant = Cloudant({
      `xxxcloudant.ibm.com`,
    plugins: [{ iamauth: { iamApiKey: `xxxxx` } }],
    })

(async () => {
    const db = await cloudant.use('db1')
    await db.insert({ msg: 'hello' })
    await cloudant.db.replicate('db1', 'db2', { create_target: true }) // will fail because this op does not use API key
})()
```

### 2. What you expected to happen
I expected the replication work successfully (OR find some documentation around this issue specifically, https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-authorization returns an empty document)
### 3. What actually happened
The replication failed saying the client was not authorized.

Instead to solve it i had to do a `cloudant.request()` and pass in the IAM key this way.

```javascript
cloudant.request({
      path: '_replicate',
      method: 'POST',
      body: {
        create_target: true,
        source: {
          url: 'source_db',
          iamauth: {
            iamApiKey: 'xxx',
          },
        },
        target: {
          url: 'target_db',
          iamauth: {
            iamApiKey: 'xxx',
          },
        },
      },
    })
```
## Environment details
- Version(s) that are affected by this issue.
    "@cloudant/cloudant": "^4.3.0"
- Node.js version
   v14.6.0

**Comment by eiri** [comment]
Auth plugins are not supported for replication, `db.replicate` requires using api key/password to compose a correct source and target urls. [ref](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-advanced-replication#authentication-during-replication).

In general we recommend to [use](https://github.com/cloudant/nodejs-cloudant/blob/master/MIGRATION.md) our new node sdk, which [does support IAM in replication](https://cloud.ibm.com/apidocs/cloudant?code=node#postreplicate).

As a work-around, as you've found out, it is possible to use `request` and pass in [replication job document](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-managing-access-for-cloudant#create-_replicator-database-source-side-ai) directly.

Thank you for pointing on dead documentation links in README.
