### ISSUE TITLE
HTTP Request Performance on Cloudant Queries

### ISSUE THREAD

**Issue by Aerex** [cloudant/nodejs-cloudant#47]
I am using the request module to send POST request to an index I made. When I try running the request through POSTman or anything that is not in Node the turnaround speed is longer than 1 second which I think is too slow. I don't know if this is cloudant issue or an issue with my code. I know I could use the index API on nodejs-cloudant but there are some features that are not available in nodejs-cloudant that are available in cradle, vice versa. I would rather not juggle between two different APIs so I decided to use the normal REST api for the features that are not available to me. If you believe that I should use nodejs-cloudant will solve my queries performance problems then I will oblige.
## Postman 356ms

![screen shot 2015-05-14 at 4 10 37 pm](https://cloud.githubusercontent.com/assets/5360960/7642085/d1322a20-fa53-11e4-875d-3b2461ccc4af.png)
## Node - 2374ms

``` javascript
request({method : 'POST', url: localUrl, json: true, headers: {'content-type' : 'application/json'}, body: filter}, function (error, response, body) {
    if(!error && response.statusCode == 200){
      console.log(query + ' time ' + (new Date() - start));
      var docs = body.docs;
      result = __generateResult(query, docs);
      def.resolve(result);
    } else {
      def.reject({'code': constants.BAD_REQUEST, 'msg': body.reason});
    }
  });
```

Thanks!

**Comment by glynnbird** [comment]
nodejs-cloudant is wrapper around the Nano Node.js library (https://github.com/dscape/nano) which itself uses the Request library to form HTTP requests. Neither nodejs-cloudant or Nano add any overhead to the process; certainly nothing that would take a second to do.

I would recommend debugging your connection using curl e.g.

    curl -v https://u:p@myaccount.cloudant.com/

It may be that DNS is taking some time to resolve, and that the POSTman is helped by the browser's DNS cache. But that's just a guess.

**Comment by jhs** [comment]
@Aerex, would you also let us know which features are missing here which Nano supports? We are always planning for future versions. Thanks!
