### ISSUE TITLE
Use Promises

### ISSUE THREAD

**Issue by bradley-holt** [cloudant/nodejs-cloudant#48]
Consider implementing promises, similar to PouchDB:
http://pouchdb.com/guides/async-code.html

A guide to implementing interoperable promises:
https://promisesaplus.com/

**Comment by jhs** [comment]
+1, thanks, Bradley.

**Comment by glynnbird** [comment]
+1, but would probably need to be done at the "Nano" level first, then we could follow suit. (e.g. cut and paste ;) )

**Comment by jhs** [comment]
We could wrap it in principle. It is pretty trivial to convert to/from promises and callbacks. However, if you are speaking more philosophically, about hewing to the Nano API (i.e. the official Apache CouchDB Node.js client), then I agree.

@bradley-holt, perhaps this would be a good candidate for a plugin?

In the bigger picture, it is unfortunate that PouchDB and Nano have different APIs? While I personally prefer the PouchDB one, @xpqz made a persuasive point that Nano is now the official CouchDB project. (And I would add it probably still has more users than PouchDB.) So I would say, have a plugin for one or both projects that simply translates to/from the PouchDB and Nano APIs. Obviously that is a future milestone :smile_cat:

**Comment by bradley-holt** [comment]
+1 on the plugin approach (for both Nano and PouchDB). I know PouchDB has a good plugin system (see <https://github.com/pouchdb/plugin-seed>, for example). How pluggable is Nano?

**Comment by jhs** [comment]
How pluggable is Nano? I am not sure how to answer the question. I think the short version is, "not very pluggable." For example, the Cloudant client could not be implemented without making changes to its source, and our future plans to refactor it to be a dependency also (barely) cannot work without changing its source.

**Comment by glynnbird** [comment]
I was able to *extend* Nano - to add functions to the core object without changing Nano itself, but I don't think something like this (implementing Promises) could be done without upstream changes.
