### ISSUE TITLE
User agent string

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#49]

**Comment by jhs** [comment]
Whoops, dupe of #1

**Comment by jhs** [comment]
Re-opening, as I think #1 is closed now

**Comment by jhs** [comment]
@mikerhodes Have you got a specific user-agent string to use?

In the meantime we will try getting the user-agent to be sent in the first place, based on our package.json package name and version.

**Comment by glynnbird** [comment]
worthwhile using `var pkg = require('./package.json');` to pick up the package name and the package version number for the user agent string

**Comment by glynnbird** [comment]
The iOS/Android libraries use this format of user-agent string:

https://github.com/cloudant/CDTDatastore/blob/master/Classes/common/touchdb/TDRemoteRequest.m#L51

Worth following that pattern. e.g. `nodejs-cloudant/2.0.0 (Node.js v0.12.2)`
