### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#5]
Nano has experimental support for running from a browser, and not only from Node.js. We could beef this up and get a second supported client platform at low effort (to both us and our users).

Now that we have CORS support, this would be pretty powerful: Web apps can start making users hit Cloudant directly from their browsers, thus simplifying our customers' work and perhaps making them more successful.

Obviously this is in the neighborhood of a 2.0 time frame, just noting it here before I forget :)

/cc @mikerhodes

**Comment by jhs** [comment]
Hi, @mikerhodes. Yes this is out of scope for your efforts, but I am making the ticket for posterity, or perhaps to work on in another capacity.

**Comment by ricellis** [comment]
Closing, we're not planning to do this. If further browser support requirements materialize we should address them in  [cloudant-node-sdk](https://github.com/IBM/cloudant-node-sdk/).
