### ISSUE TITLE
Support dotenv

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#51]
This looks like the best way to work and run tests against a real Cloudant account.

https://www.npmjs.com/package/dotenv

**Comment by glynnbird** [comment]
Yes. We should move away from hard-coded Cloudant accounts in the tests. .env is a great solution.

**Comment by jhs** [comment]
Yes, the code you mention is here: https://github.com/cloudant/nodejs-cloudant/blob/master/tests/helpers.js#L44-L48

The Cloudant account is hard-coded ("nodejs") and the password comes from npm config, for some reason.

**Comment by jhs** [comment]
Fixed in 06ff95e
