### ISSUE TITLE
Anchor links in README are not working

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#52]

**Comment by retinaburn** [comment]
FYI, I updated the anchor links and submitted a pull request for this.  Low priority, but it was bugging me ;)

**Comment by glynnbird** [comment]
Thanks for supplying the fix, I had to patch manually as the PR didn't merge automatically, but the resultant commit is here https://github.com/cloudant/nodejs-cloudant/commit/37846d713befb17a3b4561a701b427c876ecebc6

Once again, thanks for taking the time to submit a change.
