### ISSUE TITLE
Sort out Cloudant.use vs. cloudant.db.use()

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#53]
This is a wart in the API. We need to figure out what is the correct API and then

* Fix the documentation
* Ideally remove the "wrong" API, perhaps even upstream.

In my opinion, `cloudant.db.use` seems like the "right" one. That is in-line with database-related stuff (like getting a changes feed, or looking up metadata).

**Comment by rajrsingh** [comment]
+1 on `cloudant.db.use()`

**Comment by jhs** [comment]
Hi, @rajrsingh! Love it. Thanks.

**Comment by glynnbird** [comment]
Nano attaches the same function to both the top-level object and to the 'db' level. So it's just a matter of being consistent in the documentation. Fixed with the above commit.
