### ISSUE TITLE
Perhaps replace the test framework?

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#54]
Hi, @glynnbird. I was thinking, with our test suite reduced to Cloudant-only features for 2.0, what do you think about replacing the test suite with something more well-known. The Nano test suite, Specify, is more or less a custom suite written for Nano (and I believe some of Nuno's other projects).

I realize this is extra work. I guess I am weighing that work in exchange for having a more "lingua franca" test suite.

I personally like Node Tap, because it is 100% WYSIWYG (i.e. you simply run the files straight in Node, they require() some tools, and they run). However, Mocha is probably the most well-known suite, and it is more in the spirit of the current test suite (written in a synchronous-looking style).

**Comment by glynnbird** [comment]
I've used Mocha before. Together with "should" to create very readable tests. The big fault with the Nano tests is that I can't tell what they are doing. The tests should be VERY easy to read.

As we need only have tests for the Cloudant bit, then a rewrite wouldn't be too much effort.

**Comment by jhs** [comment]
Confirmed: Mocha + Should
