### ISSUE TITLE
Problem with db.view

### ISSUE THREAD

**Issue by GusETellez** [cloudant/nodejs-cloudant#55]
I have a view with a Cloudant database, whose "value" is an array of two strings. The return from db.view presents "value" as undefined. I checked the view in the DB, and I have a working ajax query that fetches the exact same data, so this looks like a bug in the code.

**Comment by jhs** [comment]
Thanks for reporting this! Can you perhaps share your design document with us, or at least your map/reduce code? And perhaps a couple of sample documents that you use with this view?

**Comment by GusETellez** [comment]
Absolutely, I can share anything you need. Let me try.

Map-reduce:
function(doc) { 
  if (doc.Appid) {
    if (doc.parents) {
      emit(doc._id, [doc.Appid, doc.parents[0]]);
    } else {
      emit(doc._id, [doc.Appid, '']);
    }
  }
}

View:
https://gusetellez.cloudant.com/testdb3/_design/turbologviewer/_view/appids

A row from the view:
{"id":"arjen_1407167426_fshlnx10ao_12985_coarse_opt_1_comp_opt_i1_1","key":"arjen_1407167426_fshlnx10ao_12985_coarse_opt_1_comp_opt_i1_1","value":["comp_opt_i1_1","arjen_1407167426_fshlnx10ao_12985"]}

**Comment by GusETellez** [comment]
A document:

{
  "_id": "arjen_1407167426_fshlnx10ao_12985_coarse_opt_1",
  "_rev": "1-d3505eaa8aeda7411f5a87ff8bf96c90",
  "Area": 290725,
  "SlewDependency": "merge-path",
  "eFOM": 120,
  "Memory": 29,
  "L2lSlk": -50.254,
  "WallTime": 13428,
  "L2lNegs": 1119,
  "WireLen": 6624512,
  "Over90": 142,
  "WstSlk": -83.696,
  "Sort_order": 19,
  "parents": [
    "arjen_1407167426_fshlnx10ao_12985"
  ],
  "NumNegs": 2501,
  "Avg20": 69.74,
  "AreaUtil": 59,
  "DefaultSlew": 18.911,
  "L2lFom": -37954.77,
  "daFOM": -86688.656,
  "CPUTime": 12794,
  "Appid": "coarse_opt_1",
  "Starting": 1407168355,
  "Gates": 31927,
  "NumSlewV": 635,
  "wACE4": 0,
  "Dynamic": 119.128,
  "Connections": 70129,
  "Ended": 1407180870,
  "Over100": 1,
  "NumCapV": 453,
  "Leakage": 35.967
}

**Comment by GusETellez** [comment]
I should point out that I am running the code from cygwin, under node.js. Perhaps this has something to do with the behaviour I am seeing.

**Comment by GusETellez** [comment]
I think this was my mistake, Javascript coding error.
