### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#61]
Is there a policy here? A `COPYING` file? Who gets the copyright attribution?

**Comment by jhs** [comment]
Specifically, what to do about the Nano

- [ ] CONTRIBUTING.md
- [ ] DCO.md
- [ ] LICENSE.md

**Comment by jhs** [comment]
I think the Apache 2.0 license.

@xpqz @mikerhodes Are you aware of the specific entity which owns the copyright, literally the string to put in the file. For example, "Copyright 2015 Cloudant, an IBM company"?

Thanks!

**Comment by jhs** [comment]
Normally in the README, just indicate the license in English

Header of source files: Copyright 2015 IBM Cloudant. All rights reserved. CDT-datastore for example.

**Comment by jhs** [comment]
Copy over CLAs from the same project

**Comment by glynnbird** [comment]
Added source header:
Commit: 01dddbffa61fcb0f7c0a31527a5049f22d9e7afc

Added CLA:
Commit: 6648092e458c3dd2f4ef8de7567d754740ebd324
