### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#64]
I named the project nodejs-cloudant mostly as a working title. At least, I did not put any thought into it. (I usually name my projects the most straightforward thing possible, as they accumulate and cutesy names do not jog the memory like obvious ones do.)

Anyway, 2.0 may be a good place to rename, or to standardize the name with the other Cloudant client projects.

**Comment by glynnbird** [comment]
The npm name is 'cloudant' which makes sense, but as this project belongs in the 'cloudant' github repo, it needs a github name that makes sense for people looking in that account, so it can't be called 'cloudant' there. 

There isn't much of an overarching scheme in the other library projects:

* CDTDatastore - the iOS library
* sync-android - the Android library
* java-cloudant - the Java library

java-cloudant is not far off nodejs-cloudant, though. 

Any thoughts @xpqz @mikerhodes ?

**Comment by jhs** [comment]
Good point, I forgot that this is only really a GitHub issue, much less serious than I thought.

**Comment by jhs** [comment]
For the sake of clearing out the growing issue backlog, I'll just close this. If somebody beyond my pay grade wishes to change the name, they are welcome.
