### ISSUE TITLE
Should should?

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#65]
Discuss should vs. assert. By no means do I want to bike shed. But I wonder if "should" is running against the philosophy of super clear, straightforward tests.

For now, I am proceeding with Should. Certainly, I want to log more hours with it.

**Comment by jhs** [comment]
``` javascript
    Cloudant({account:'nodejs'}, function(er, cloudant, body) {
      should(er).equal(null, 'No problem pinging Cloudant');

      cloudant.should.be.type('object', 'Cloudant client object returned');
      (body && body.version).should.be.ok;
      (body && body.userCtx).should.be.ok;

      done();
    });
```

**Comment by jhs** [comment]
``` javascript
    Cloudant({account:'nodejs'}, function(er, cloudant, body) {
      assert.equal(er, null, 'No problem pinging Cloudant');

      assert.equal(typeof cloudant, 'object', 'Cloudant client object returned');
      assert.ok(body && body.version, 'Pong includes the server version');
      assert.ok(body && body.userCtx, 'Pong includes the userCtx');

      done();
    });
```

**Comment by glynnbird** [comment]
I think should wins on things like

    body.doc.should.be.an.Object;
    body.doc.should.have.property("fred", "the document should contain fred").with.length(4);

Perhaps if your 'should' code read more like this commit:

https://github.com/cloudant/nodejs-cloudant/commit/b3553d603db7db71073392b43c6dbae8ba3da838

?

**Comment by jhs** [comment]
Love it. Let's proceed while I get my Should sea-legs.
