### ISSUE TITLE
Nock style

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#66]
Nock is much nicer and simpler than I thought when I learned it from Nano. Nano has a very nice, very powerful Nock and fixture system. But I am now attracted to the very simple Nock usage, which is very explicit and clear.

I think we all agree, just load the Nock responses right in the test file, e.g. `tests/api.js`.

Where I am unsure is the style of that file. I see three options:

1. Prep a mock responses immediately before running a test. This is what I am doing now, see api.js in the "ping" tests.
2. Have a huge "preamble" where all of the server responses are loaded up at the top of the file, then all the tests below just run naturally.

Possibly a 2b option would be like option 2, but instead of a preamble, it is an "appendix", meaning that we can write a function way at the bottom where all the hard-coded stuff is, but then call it from the top. (Thanks, JobamaScript!)

Pseudocode example to clarify:

``` javascript
// api.js

mock()

describe("First test", function() {
  it("does something", function() {
     // etc.
     // etc.
  });
});

describe("etc. etc.") // ...

mock() {
    nock(URL).get('/').reply(200, {couchdb:"Welcome", version:"1.0.2"});
    nock(URL).get('/_session').reply(200, {userCtx:{...}});
    // etc.
    // etc.
    // etc.
}
```

**Comment by glynnbird** [comment]
I like the idea of responses being next to the test - you don't have to go hunting for where they live.

If we do need to some setup before a number of tests run, then we can use Mocha's hooks:

```
describe('hooks', function() {
  before(function() {
    // runs before all tests in this block
  })
  after(function(){
    // runs after all tests in this block
  })
  beforeEach(function(){
    // runs before each test in this block
  })
  afterEach(function(){
    // runs after each test in this block
  })
  // test cases
})
```

so that before, beforeEach etc can be used to setup the test conditions. We should aim for the tests to clean up after themselves - deleting any test data and restoring the test cluster back to the state it was in.
