### ISSUE TITLE
Where is the set_permissions test?

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#68]
I want to remove `tests/fixtures/` one-by-one as we get them actually in the tests. (In that way, it is a bit of a checklist to make sure we test everything we used to.)

Where is the /api/set_permissions test? Is it the `_security` object update, currently line 150 of api.js?

**Comment by glynnbird** [comment]
The set_permissions function is deprecated see the code in cloudant.js

```
  var set_permissions = function(opts, callback) {
    console.error("set_permissions is deprecated. use set_security instead");
    callback(null, null);
  };
```
