### ISSUE TITLE
A different database per "describe" section

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#70]
To clarify and hopefully help track down future errors, perhaps rather than MYDB maybe we use MYDB+"_query" for testing Cloudant Query, _search for search, etc.

**Comment by glynnbird** [comment]
We could do, but each test group (search, query etc) creates the database in the 'before' question and destroys it in the 'after' section, so under the hood a different database would be created.

What do you think?

**Comment by jhs** [comment]
Good point. It works as-is. No need to create work for ourselves.
