### ISSUE TITLE
Cannot call method 'apply' of undefined, after socket hang up error

### ISSUE THREAD

**Issue by mheitzibm** [cloudant/nodejs-cloudant#71]
I'm using Cloudant 1.0.0 on Bluemix with Node 0.10.38.  The following error was thrown.

> TypeError: Cannot call method 'apply' of undefined
>     at Socket.emit (events.js:117:20)
>     at TCP.close (net.js:466:12)

That's the entire stack trace.  It happened after another error (below), which I handled.  The error above *couldn't be handled* because it was not thrown by a Cloudant function that I called.  It seems to have come from some event handler of yours.

This is the original error.  I'm not asking for it to be fixed or explained, just including it in case it helps you solve the error above.

> Error: socket hang up,
>     at SecurePair.error (tls.js:1014:23),
>     at EncryptedStream.CryptoStream._done (tls.js:706:22),
>     at CleartextStream.read [as _read] (tls.js:502:24),
>     at CleartextStream.Readable.read (_stream_readable.js:341:10),
>     at EncryptedStream.onCryptoStreamFinish (tls.js:307:47),
>     at EncryptedStream.g (events.js:180:16),
>     at EncryptedStream.emit (events.js:117:20),
>     at finishMaybe (_stream_writable.js:360:12),
>     at endWritable (_stream_writable.js:367:3),
>     at EncryptedStream.Writable.end (_stream_writable.js:345:5),
>     at EncryptedStream.CryptoStream.end (tls.js:644:31),
>     at Socket.onend (_stream_readable.js:502:10),
>     at Socket.g (events.js:180:16),
>     at Socket.emit (events.js:117:20),
>     at _stream_readable.js:944:16,
>     at process._tickDomainCallback (node.js:492:13)`

**Comment by glynnbird** [comment]
The stack trace looks to be at a pretty low level - in the TLS stream layer. Is it possible for you to isolate the problem to a small snippet of code that causes the error to be thrown?

**Comment by mheitzibm** [comment]
Sorry, I really can't pin it down.  It has only happened a few times and I don't know the exact circumstances that make it happen.

Is there a way to turn on logging in the cloudant module, or something else that would let us collect more information?

**Comment by glynnbird** [comment]
In the next version of nodejs-cloudant (due out on 30th June), you can do

    export DEBUG=cloudant

before running your code which will ask the library to generate debugging output.

**Comment by mheitzibm** [comment]
Thanks, I'll try that and get back to you.

**Comment by mheitzibm** [comment]
What will be the impact on performance if I turn on the debugging output?

**Comment by glynnbird** [comment]
It will have a small impact, but it's just outputing text to stdout, so nothing too much. It is not recommended tht you use DEBUG in production, unless you are looking to isolate a particular issue.

**Comment by mheitzibm** [comment]
We haven't seen the problem since I opened this issue.

**Comment by glynnbird** [comment]
Thanks for letting me know. I'll close this issue now, but feel free to open a new one if you get another problem.
