### ISSUE TITLE
Look into the "shot" package for unit testing

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#73]
Hapijs uses this. Generally speaking, Hapi has a good reputation for running a disciplined project. `shot` is part of that project.

https://github.com/hapijs/shot#readme

This issue is for posterity, so I remember the package. It kind of looks like a counterpart to `nock`. Nock intercepts outgoing http requests so that you can test a client without worrying about networking. Shot injects incoming http requests into a server, so that you can test a server without worrying about networking.

In the future, it looks clear that we will want unit tests to make sure that we are sending correct data to Cloudant. If we ever need a server to simulate Cloudant, maybe this can help.

**Comment by ricellis** [comment]
Closing. Our current thinking for this type of testing is to use a common server across all the integration libraries, rather than a specific unit test server implementation for each one.
