### ISSUE TITLE
Contribute to upstream Nano to fix debugging

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#77]
I spotted a but in Nano. @jhs & I fixed it with this PR: https://github.com/dscape/nano/pull/286

Hopefully we can get this PR accepted, then we can depend on _that_ Nano version.

**Comment by glynnbird** [comment]
@jhs has contributed to the discussion about dscape/nano#286.

**Comment by glynnbird** [comment]
Who knows what will happen to this PR as it is sitting on the dscape/nano repo which is now no longer the *real* nano repository!

**Comment by jhs** [comment]
This is not blocking the 1.2 launch I don't think so let me move it back to clear out the 1.2 milestone

**Comment by ricellis** [comment]
Closing, if logging is still broken in nano, we should raise the issue there.
