### ISSUE TITLE
Connection pool not working

### ISSUE THREAD

**Issue by jonface** [cloudant/nodejs-cloudant#78]
Setup the agent and connection,

```
var agentkeepalive = require('agentkeepalive');
var myagent = new agentkeepalive({
                                     maxKeepAliveRequests: 50,
                                     maxKeepAliveTime: 30000,
                                     maxSockets: 100,
                                     maxFreeSockets: 10,
                                     timeout: 60000,
                                     keepAliveTimeout: 30000
                                 });

var cloudant = require('cloudant')({
                                       account: "me",
                                       key: 'key',
                                       password: 'pass',
                                       request_defaults: {agent: myagent}
                                   }, function (er, cloudant, reply)
                                   {
                                       console.log('Connected with username: %s', reply.userCtx.name);
                                   }
```

Strange thing is, if I watch in wireshark, I can see the TCP connections SYN then after the request completes the FIN . Surely this isn't correct? Am I doing something wrong?

node 0.10.35

Thanks

**Comment by glynnbird** [comment]
Remember that traffic to Cloudant is over HTTPS. The code above creates a custom HTTP agent. The documentation for `agentkeepalive` describes how to create an HTTPS agent here: https://github.com/node-modules/agentkeepalive

**Comment by jonface** [comment]
The README prob needs updating as I just did a copypasta from it.

I need to do further testing but after changing to the HTTPS agent, I still noticed the connection tearing down. Is it possible someone who knows what they are doing, verify that it does work correctly using wireshark? And if so, which node version?

Thanks

**Comment by jonface** [comment]
Nope same issue, someone else want to try? Ta

**Comment by jhs** [comment]
We will add unit tests to confirm or disconfirm the behavior as documented. Thanks for bringing this to our attention!

**Comment by glynnbird** [comment]
This is a documentation problem. Request defaults are passed through as "requestDefaults", not "request_defaults" as stated in the documentation. Here comes the fix.

**Comment by jhs** [comment]
Fixed in f8536c1; Please let us know if you have any further issues, @jonface

**Comment by jonface** [comment]
Amazing,

(Only thing which changed during test was the keepalive agent enabled/disabled. Times include various overheads but are comparable.)

With keepalive NOT working, the response time is around 450ms and greater .
With keepalive working, response time is around 120ms - 160ms.

With keepalive NOT working, I could see in wireshark the connection SYN then FIN.
With keepalive working, the connection was setup and stayed connected after the request ended. TCP keepalives were sent during idle periods.

With these response times now, if it wasn't for the cost savings, I'd disable my memcache layer.

Thanks

**Comment by glynnbird** [comment]
This is now released, so closing.
