### ISSUE TITLE
Tests for gzipped transfer-encoding on attachments

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#81]

**Comment by glynnbird** [comment]
This test verifies that our "accepts-encoding: gzip" header advises Cloudant that we will accept any gzipped responses. For now, Cloudant only gzips certain attachments ( ones whose mime-types match text/*, application/javascript, application/json,  application/xml), so this test simulates a gzipped attached CSS file and ensures that the db.attachment.get function successfully unzips a zipped response.
