### ISSUE TITLE
Use of Old version of `follow` prevents use of latest node runtime

### ISSUE THREAD

**Issue by AndrewHuffman** [cloudant/nodejs-cloudant#83]
Follow versions < v0.12 do not support the latest node runtime (v0.12.x), are there plans to move to the latest version?

**Comment by AndrewHuffman** [comment]
Anyone?

**Comment by glynnbird** [comment]
nodejs-cloudant depends on nano 6.1.4 (shortly 6.1.5) which depends on the latest follow 0.12.1. So unless I'm mistaken, this project is pretty much up-to-date?

**Comment by AndrewHuffman** [comment]
Ah, sorry about that, the versions confused me. I was looking at what I thought was the latest tagged release (v5.12.1) but it appears the latest release is v1.2.0.

**Comment by glynnbird** [comment]
No problem Andrew,
