### ISSUE TITLE
Only reserved document ids may start with underscore

### ISSUE THREAD

**Issue by gabrielmancini** [cloudant/nodejs-cloudant#84]
Guys i am trying to insert a _security document on cloudant using cloudant.db.insert(ddoc, cb)

and i give:

```
Only reserved document ids may start with underscore
```

some gotcha here?

**Comment by glynnbird** [comment]
You can't modify the access to a database in this way. The API you need is this one [this one](https://docs.cloudant.com/authorization.html) which is available as the [set_security](https://github.com/cloudant/nodejs-cloudant#authorization-and-api-keys) api call in this library.
