### ISSUE TITLE
Enforce HTTPS only

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#86]
Bob Newson recommends we adopt an HTTPS-only policy in this library: discuss

**Comment by mikerhodes** [comment]
Split session cookies into another issue.

**Comment by glynnbird** [comment]
Done @mikerhodes . There is now an issue #87 too.

**Comment by glynnbird** [comment]
Ok. We decided to force https, when the domain name is a "*cloudant.com".

**Comment by jhs** [comment]
Love it.

What specific changes does this ticket require then? Don't we already force https? See https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L28-L45

If I am reading the code right: during init, if the user supplies a `*.cloudant.com`, or if they provide a `.account` option, then we use https.

So, @glynnbird or @mikerhodes what is an example of a situation we are doing wrong at present? Thanks.

**Comment by jhs** [comment]
One modest idea, to begin, is to have a unit test for that `reconfigure()` function. We can confirm that, for various inputs, the actual final URL used is indeed https

**Comment by glynnbird** [comment]
Currently we warn if users are passing credentials over HTTP. As a result of this ticket, if a user is using this library against a "*cloudant.com" domain name, was want to force https. This still allows local development over http.

**Comment by jhs** [comment]
@glynnbird Right. My point is, the code already does everything you describe, as far as I can see. So what change to the code does this ticket demand, then?

**Comment by glynnbird** [comment]
The current state of play is:

* if you instantiate with account and password, we construct a Cloudant URL and force HTTPS
* if you instantiate with a full URL, we don't force HTTPS, we only warn if you passing credentials of http

As a result of this ticket, we want to force HTTPS when communicating with a "*cloudant.com" domain, however you instantiate.

**Comment by jhs** [comment]
Okay, just from this conversation, I think some unit tests will clearly help, to set our policy in stone as it were and to prevent any unfortunate regressions.

And yes, _mea malum_, I read the code incorrectly. (Good thing I'm not a JavaScript virtual machine, I'd be sacked for sure!) Reading `reconfigure()`, I thought there was no way to get a plaintext URL however I forgot that we can initialize with a string alone, which bypasses the reconfiguration step.

https://github.com/cloudant/nodejs-cloudant/blob/master/cloudant.js#L62-L72

**Comment by jhs** [comment]
Implemented and ready for testing/publishing. Push forthcoming once I get my laptop back
