### ISSUE TITLE
Use session cookies rather than passing credentials with each request

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#87]
Bob Newson recommends we use session cookies to login, instead of passing username/password with each request.

In the near future, Cloudant may penalise username/password logins with a delay making it much more performant to use the cookie method.

**Comment by glynnbird** [comment]
This is essential work. @mikerhodes describes an interceptor of all requests.

**Comment by jhs** [comment]
Whatever we do in #85 to clean out credentials from errors, we may want to double-check how that all works here too.

**Comment by glynnbird** [comment]
As far as I can see, this would require us to allow a user to create a Cloudant object passing in username & password (or account and password) and we (the library) would do a `cloudant.auth` call to exchange the credentials for a cookie. 

We would then need to intercept each reply, to see if Cloudant has issued a new cookie value (which it will periodically). We would also need to deal with the case of someone creating a Cloudant object, sleeping for 24 hours and then using the library, in which case the cookie would be stale.

It seems the best place to do this is in the `relax` function in Nano - if we can put the cookie logic in there, then all API requests could be intercepted. I've tried to intercept this call from within our library but with no success.

**Comment by jhs** [comment]
Implemented in Nano on my laptop branch; push forthcoming.
