### ISSUE TITLE
Cloudant search - non-intuitive handling of counts parameter

### ISSUE THREAD

**Issue by glynnbird** [cloudant/nodejs-cloudant#89]
In the sample code below

```
var cloudant = require('cloudant')('https://reader.cloudant.com');
var guitars = cloudant.db.use('guitars');


guitars.search('search', 'search', {q:'*:*',limit:0, counts: ["brand"] }, function(err, data) {
  if (err)
    throw err
  console.log(err,data);
});
```

instead I have to do:

```
guitars.search('search', 'search', {q:'*:*',limit:0, counts: JSON.stringify(["brand"]) }, function(err, data) {
 ...
```

I think our library should detect if `counts` is provided as an array and JSON.stringify it for the user.

**Comment by glynnbird** [comment]
Agreed to do this, because it's helpful.

**Comment by jhs** [comment]
Oh weird, we have to supply `{counts:'["brand"]', ...}`? Yes that is odd.

**Comment by glynnbird** [comment]
This would need doing in the Nano project.

**Comment by glynnbird** [comment]
Looking more closely at this, `counts` is not the only parameter that Cloudant expects to be passed as a JSON string and that the user of this library may expect to be able to pass in as an array or an object. For the Cloudant search API we have

- counts e.g. counts=["brand","colour"]
- drilldown e.g. drilldown=["brand",fender"]&drilldown=["colour","red"]
- group_sort 
- ranges e.g ranges={"price": {"expensive": 278682,"cheap": 257023}}
- sort e.g. sort="-price<number>"

It would seem odd to do this ticket for `counts` but leave the other fields as they are. What do we thing?

I was going to suggest something like:

```
  for(var i in qs) { 
    if (typeof qs[i] !== "string") { 
      qs[i] = JSON.stringify(qs[i]); 
    }
  }
```

but where does that leave things like `sort` which are stringified strings?

**Comment by jhs** [comment]
Fixed in Nano. @glynnbird Is the list you made above comprehensive?

**Comment by glynnbird** [comment]
It's comprehensive for the `search` function and its underlying endpoint @jhs

**Comment by kaushik-evani** [comment]
Hi. I have encountered a similar issue with the parameters "group_field" and "sort" as well. They dont seem to be working with the node APIs but they do work perfectly fine if I directly use cloudant's http APIs. For example,
guitars.search('search', 'search', {q:'*:*', group_field: "brand", sort: "manufactureDate" }, function(err, data) {
      // Some code here
});
For the above code it does not return any rows.
Thanks a lot.
