### ISSUE TITLE
proxy from pouchdb-authentication 

### ISSUE THREAD

**Issue by gabrielmancini** [cloudant/nodejs-cloudant#92]
Hy Guys i wondering if we can create a proxy from pouchdb-authentication plugin to cloudant
some like this.
pouchdb+pouchdb-authentication ----> node+nodejs-cloudant /proxy ------> cloudant

**Comment by glynnbird** [comment]
If you're interested in creating a Node.js proxy, you can do it without using hte nodejs-cloudant library:

https://cloudant.com/blog/cors-and-reverse-proxies-in-node-js-express/

Also, if you're using PouchDB in the browser, you can communicate directly with Cloudant, without going through any middle man as long as CORS is enabled on the Cloudant side:

```
  var remote = new PouchDB("https://myuser:mypass@myaccount.cloudant.com/mydb");
  remote.allDocs(...);
```

**Comment by gabrielmancini** [comment]
but the api to authenticate its diferent between cloudant and couchdb i am thinking in a way to remove that differences with this proxy... the most part its only a simple proxy, but the security, authentication autorization... made some ajustments to mimify the couchdb behaviour.

**Comment by jhs** [comment]
Neat!

@gabrielmancini Can you help me make sure I understand?

Do you want PouchDB users to use Cloudant with the same plugins and JavaScript code they are used to?

**Or,**

Do you want Node.js-Cloudant users to authenticate to Cloudant using the nodejs-client + the pouchdb-authentication plugin?

Thanks!

**Comment by gabrielmancini** [comment]
i think is the 2 things...

i want to mimicry the behaviour of the cocuhdb using this proxy and the follow capabilities and ba able to use any piece of code to runing on couchdb to run on cloudant without any changes...

**Comment by ricellis** [comment]
Closing as stale.
