### ISSUE TITLE
Test suite fails if "mydb" already exists

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#93]
If "mydb" is already a database in my Cloudant (which can happen if the test suite or Internet crashes halfway through running), then it will fail again, since that first PUT "mydb" will return an error.

**Comment by jhs** [comment]
The workaround of course is to just manually delete the DB, then carry on

**Comment by smithsz** [comment]
Added `@afterEach` hooks to ensure test databases get removed.
