### ISSUE TITLE
Automatically use cookie authentication when possible

### ISSUE THREAD

**Issue by jhs** [cloudant/nodejs-cloudant#94]
I just noticed this: https://docs.cloudant.com/authentication.html

    When creating or using performance critical Cloudant applications, Cookie authentication
    has benefits compared with Basic authentication. Therefore, you should prefer Cookie
    authentication where possible.

We could easily do this in the background, and switch to cookie authentication if it works, for a free performance boost to users. Or, certainly with the callback-style API, because we are already querying `/_session`, so we may as well remember that Set-Cookie header.

**Comment by glynnbird** [comment]
Same thing as #87?

**Comment by jhs** [comment]
Yep! Dupe of #87.
